export const CAPTION_STYLE_PRESETS = {
  active_word_highlight: {
    id: "active_word_highlight",
    name: "Current Active Word",
    description:
      "Full caption block stays visible while only the currently spoken word turns blue.",
    uppercase: true,
    maxLines: 1,
    maxWordsPerCue: 4,
    minWordsPerCue: 2,
    maxCharsPerLine: 30,
    minCueDurationSec: 0.55,
    maxCueDurationSec: 2.2,
    inactiveColor: "#FFFFFF",
    activeColor: "#00D9FF",
    outlineColor: "#000000",
    outlineWidth: 8,
    shadowColor: "#000000",
    shadowBlur: 4,
    position: "bottom_center",
    bottomMarginPercent: 12,
    fontFamily: "Arial",
    fontWeight: 900,
    fontSize: 64,
    marginV: 90,
    preserveQuestionMarks: true,
    preserveExclamationMarks: true,
    preserveEllipsis: false,
    removeCommas: false,
    removeFinalPeriods: false,
    removeQuotes: false,
    phraseMode: "legacy",
    italic: false,
    matchScriptCasing: false,
    hookPreferredWordsPerCue: 4,
    bodyPreferredWordsPerCue: 5,
    hookMaxCharsPerCue: 30,
    bodyMaxCharsPerCue: 32,
  },
  clean_active_word: {
    id: "clean_active_word",
    name: "Clean Active Word",
    description:
      "Phrase-based uppercase captions with cleaner display text and active-word highlight.",
    uppercase: true,
    maxLines: 1,
    maxWordsPerCue: 5,
    minWordsPerCue: 2,
    maxCharsPerLine: 28,
    minCueDurationSec: 0.55,
    maxCueDurationSec: 2.4,
    inactiveColor: "#FFFFFF",
    activeColor: "#FFD84D",
    outlineColor: "#000000",
    outlineWidth: 4,
    shadowColor: "#000000",
    shadowBlur: 1,
    position: "bottom_center",
    bottomMarginPercent: 12,
    fontFamily: "Arial",
    fontWeight: 900,
    fontSize: 60,
    marginV: 90,
    preserveQuestionMarks: true,
    preserveExclamationMarks: false,
    preserveEllipsis: false,
    removeCommas: true,
    removeFinalPeriods: true,
    removeQuotes: true,
    phraseMode: "clean",
    italic: false,
    matchScriptCasing: false,
    hookPreferredWordsPerCue: 4,
    bodyPreferredWordsPerCue: 6,
    hookMaxCharsPerCue: 28,
    bodyMaxCharsPerCue: 38,
  },
  clean_phrase: {
    id: "clean_phrase",
    name: "Clean Phrase",
    description:
      "Clean phrase captions without word-by-word emphasis for calmer sections.",
    uppercase: true,
    maxLines: 2,
    maxWordsPerCue: 7,
    minWordsPerCue: 2,
    maxCharsPerLine: 38,
    minCueDurationSec: 0.7,
    maxCueDurationSec: 3.6,
    inactiveColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 3,
    shadowColor: "#000000",
    shadowBlur: 1,
    position: "bottom_center",
    bottomMarginPercent: 12,
    fontFamily: "Arial",
    fontWeight: 900,
    fontSize: 58,
    marginV: 90,
    preserveQuestionMarks: true,
    preserveExclamationMarks: false,
    preserveEllipsis: false,
    removeCommas: true,
    removeFinalPeriods: true,
    removeQuotes: true,
    phraseMode: "clean",
    italic: false,
    matchScriptCasing: false,
    hookPreferredWordsPerCue: 4,
    bodyPreferredWordsPerCue: 6,
    hookMaxCharsPerCue: 28,
    bodyMaxCharsPerCue: 38,
  },
  clean_phrase_script: {
    id: "clean_phrase_script",
    name: "Clean Phrase (script case)",
    description:
      "Same clean phrase rhythm as Clean Phrase, but keeps scriptText capitalization and renders in italics.",
    uppercase: false,
    maxLines: 2,
    maxWordsPerCue: 7,
    minWordsPerCue: 2,
    maxCharsPerLine: 38,
    minCueDurationSec: 0.7,
    maxCueDurationSec: 3.6,
    inactiveColor: "#FFFFFF",
    activeColor: "#FFFFFF",
    outlineColor: "#000000",
    outlineWidth: 3,
    shadowColor: "#000000",
    shadowBlur: 1,
    position: "bottom_center",
    bottomMarginPercent: 12,
    fontFamily: "Arial",
    fontWeight: 700,
    fontSize: 58,
    marginV: 90,
    preserveQuestionMarks: true,
    preserveExclamationMarks: false,
    preserveEllipsis: false,
    removeCommas: true,
    removeFinalPeriods: true,
    removeQuotes: true,
    phraseMode: "clean",
    italic: true,
    matchScriptCasing: true,
    hookPreferredWordsPerCue: 4,
    bodyPreferredWordsPerCue: 6,
    hookMaxCharsPerCue: 28,
    bodyMaxCharsPerCue: 38,
  },
  godsword_style: {
    id: "godsword_style",
    name: "GodsWord Style",
    description:
      "White captions with wheat-gold active words matching TheGodsWord parchment illustration palette.",
    uppercase: true,
    maxLines: 1,
    maxWordsPerCue: 5,
    minWordsPerCue: 2,
    maxCharsPerLine: 28,
    minCueDurationSec: 0.55,
    maxCueDurationSec: 2.4,
    inactiveColor: "#FFFFFF",
    // Muted wheat gold from the channel image bible (parchment / earth tones).
    activeColor: "#C9A84C",
    outlineColor: "#000000",
    outlineWidth: 4,
    shadowColor: "#000000",
    shadowBlur: 1,
    position: "bottom_center",
    bottomMarginPercent: 12,
    fontFamily: "Arial",
    fontWeight: 900,
    fontSize: 60,
    marginV: 90,
    preserveQuestionMarks: true,
    preserveExclamationMarks: false,
    preserveEllipsis: false,
    removeCommas: true,
    removeFinalPeriods: true,
    removeQuotes: true,
    phraseMode: "clean",
    italic: false,
    matchScriptCasing: false,
    hookPreferredWordsPerCue: 4,
    bodyPreferredWordsPerCue: 6,
    hookMaxCharsPerCue: 28,
    bodyMaxCharsPerCue: 38,
  },
} as const;

export type CaptionStylePresetId = keyof typeof CAPTION_STYLE_PRESETS;
export type CaptionStylePreset =
  (typeof CAPTION_STYLE_PRESETS)[CaptionStylePresetId];

export const DEFAULT_CAPTION_STYLE_PRESET_ID = "active_word_highlight";

export function getCaptionStylePreset(
  id: string | null | undefined,
): CaptionStylePreset {
  if (id && id in CAPTION_STYLE_PRESETS) {
    return CAPTION_STYLE_PRESETS[id as CaptionStylePresetId];
  }

  return CAPTION_STYLE_PRESETS[DEFAULT_CAPTION_STYLE_PRESET_ID];
}
