import {
  extractJsonPayload,
  extractScoreJsonObject,
} from "@/lib/browser-automation/types";
import { getChannelProfile } from "@/lib/channels-server";
import {
  PODCAST_ENGLISH_LESSONS_CHANNEL_KEY,
  PODCAST_SCRIPT_WRITER_MAX_DRAFTS,
  PODCAST_SCRIPT_WRITER_PASS_SCORE,
  buildMaxSaraGoldStandardPromptBlock,
  buildPodcastGoldStandardPromptBlock,
  resolvePodcastEpisodeFormat,
  type PodcastEpisodeFormat,
} from "@/lib/podcast-english-lessons-script-shared";
import { stripChatGptUiChrome } from "@/lib/script-writer-extract";
import {
  buildPromptSections,
  readProjectText,
  type ScriptWriterEpisodeContext,
} from "@/lib/script-writer-prompt-context";

/** Keep the latest draft only when ChatGPT scores strictly above this. */
export const SCRIPT_WRITER_PASS_SCORE = 9.2;

/** Safety cap for generic channels. Podcast / Wealth override via getters. */
export const SCRIPT_WRITER_MAX_DRAFTS = 5;

/** Wealth Insights: V1 + one same-chat revision, then keep the last draft. */
export const WEALTH_SCRIPT_WRITER_MAX_DRAFTS = 2;

export {
  PODCAST_SCRIPT_WRITER_MAX_DRAFTS,
  PODCAST_SCRIPT_WRITER_PASS_SCORE,
};

const PRECEDING_ASSISTANT_SCRIPT_SCORE_RULES = `Evaluate the complete narration script contained in the immediately preceding assistant message.

Score that exact script. Do not evaluate the instructions, episode brief, earlier drafts, evaluator prompts, or any other message in the conversation.

Do not include, quote, summarize, or reproduce the script itself in the response.`;

const GENERIC_SCRIPT_WRITER_SCORE_PROMPT = `You are evaluating a YouTube narration script.

${PRECEDING_ASSISTANT_SCRIPT_SCORE_RULES}

Do not reward or penalize it for being an early draft.

Score THAT LATEST script honestly from 0 to 10 (one decimal allowed) for:
- hook strength in the opening
- clarity and originality of the mechanism
- emotional pacing and retention
- speakability for voiceover (natural spoken English)

Reply with ONLY valid JSON (no markdown fences, no extra text):
{"score": 8.4, "briefReason": "one short sentence naming the main weakness or strength", "dimensionScores": {"hook": 8.0, "architecture": 8.0, "practice": 8.0, "dialogue": 8.0, "repetitionRhythm": 8.0, "level": 8.0, "completeness": 8.0}, "strengths": ["..."], "mustFix": ["..."], "rewritePriority": ["..."]}`;

const GENERIC_SCRIPT_WRITER_REVISION_PROMPT = `You are revising a YouTube narration script.

Revise the most recent complete narration script previously generated by the assistant in this conversation.

Use the evaluation JSON contained in the immediately preceding assistant message as the revision brief.

Apply every item in mustFix.

Use rewritePriority to determine where the highest-impact changes are needed.

Use the value of decision when present to determine the revision depth:

* polish: Make targeted edits only. Preserve everything that already works. Do not restructure the whole script. If unsure, keep the previous wording.
* rewrite: Make meaningful structural changes while using the existing script as the foundation.
* regenerate: Produce a substantially new draft based on the original episode brief and the scorer’s findings.

Rules:
- Output ONLY the plain narration script text
- Do NOT wrap the script in JSON (no {"script":"..."}, no {"score":...})
- No title, no score, no preamble, no bullet notes, no markdown fences, no draft label
- Keep it speakable for voiceover
- Preserve the core idea, but improve specifically what the critique called out
- The revised draft must not be weaker overall than the previous script
- Do not mention the score, scorer, critique, revision process, draft number, or evaluation JSON in the narration
- Do not include the previous script or evaluation in the response`;

const markdownPromptCache = new Map<string, string>();

async function readOptionalPromptMarkdown(relativePath: string | undefined) {
  const trimmed = relativePath?.trim();
  if (!trimmed) {
    return null;
  }

  const cached = markdownPromptCache.get(trimmed);
  if (cached != null) {
    return cached;
  }

  try {
    const text = await readProjectText(trimmed);
    markdownPromptCache.set(trimmed, text);
    return text;
  } catch {
    return null;
  }
}

export function getScriptWriterMaxDrafts(channelKey?: string | null) {
  if (channelKey === PODCAST_ENGLISH_LESSONS_CHANNEL_KEY) {
    return PODCAST_SCRIPT_WRITER_MAX_DRAFTS;
  }
  if (channelKey === "wealth-insights") {
    return WEALTH_SCRIPT_WRITER_MAX_DRAFTS;
  }
  return SCRIPT_WRITER_MAX_DRAFTS;
}

export function getScriptWriterPassScore(channelKey?: string | null) {
  if (channelKey === PODCAST_ENGLISH_LESSONS_CHANNEL_KEY) {
    return PODCAST_SCRIPT_WRITER_PASS_SCORE;
  }
  return SCRIPT_WRITER_PASS_SCORE;
}

/** @deprecated Prefer getScriptWriterScorePrompt(channelKey, options). */
export const SCRIPT_WRITER_SCORE_PROMPT = GENERIC_SCRIPT_WRITER_SCORE_PROMPT;

export async function getScriptWriterScorePrompt(
  channelKey?: string | null,
  options?: {
    script?: string | null;
    validationReport?: string | null;
    projectBible?: string | null;
    currentIdeaJson?: unknown;
    episodeContext?: ScriptWriterEpisodeContext | null;
  },
) {
  if (channelKey === PODCAST_ENGLISH_LESSONS_CHANNEL_KEY) {
    return buildPodcastScorePrompt(options);
  }

  const channel = channelKey ? getChannelProfile(channelKey) : null;
  const scoreMarkdown = await readOptionalPromptMarkdown(
    channel?.prompts.scriptWriterScore,
  );

  if (scoreMarkdown && channelKey === "wealth-insights") {
    // Same-thread scoring: evaluate the preceding assistant script. Do not
    // re-attach Project Bible / Idea JSON / full script (keeps prompt under
    // ChatGPT's inline threshold so it is not uploaded as a .md file).
    return buildPromptSections([
      ["Script Writer Score Prompt", scoreMarkdown],
      ["Scoring Rules", PRECEDING_ASSISTANT_SCRIPT_SCORE_RULES],
    ]);
  }

  if (scoreMarkdown) {
    return scoreMarkdown;
  }

  return GENERIC_SCRIPT_WRITER_SCORE_PROMPT;
}

function resolvePodcastFormatForCritique(options?: {
  validationReport?: string | null;
  currentIdeaJson?: unknown;
  episodeContext?: ScriptWriterEpisodeContext | null;
}): PodcastEpisodeFormat {
  const fromContext =
    options?.episodeContext?.podcastEpisodeFormat ??
    (options?.episodeContext?.episodeMode === "max_sara_conversation" ||
    options?.episodeContext?.episodeMode === "emma_leo_lesson"
      ? options.episodeContext.episodeMode
      : null);
  if (
    fromContext === "max_sara_conversation" ||
    fromContext === "emma_leo_lesson"
  ) {
    return fromContext;
  }

  const fromReport = options?.validationReport?.match(
    /Format:\s*(max_sara_conversation|emma_leo_lesson)/i,
  )?.[1];
  if (fromReport === "max_sara_conversation" || fromReport === "emma_leo_lesson") {
    return fromReport;
  }
  return resolvePodcastEpisodeFormat({
    channelKey:
      options?.episodeContext?.channelKey ?? PODCAST_ENGLISH_LESSONS_CHANNEL_KEY,
    ideaJson: options?.currentIdeaJson,
    title: options?.episodeContext?.videoTitle,
    topic: options?.episodeContext?.topic,
  });
}

function buildPodcastScorePrompt(options?: {
  script?: string | null;
  validationReport?: string | null;
  currentIdeaJson?: unknown;
  episodeContext?: ScriptWriterEpisodeContext | null;
}) {
  const format = resolvePodcastFormatForCritique(options);
  const validationBlock = options?.validationReport?.trim()
    ? `

DETERMINISTIC VALIDATION REPORT (treat errors as hard evidence; apply score caps):
${options.validationReport.trim()}
`
    : "";

  if (format === "max_sara_conversation") {
    return `You are scoring a Podcast English Lessons script (Natural Daily English Conversations with Max & Sara).

${PRECEDING_ASSISTANT_SCRIPT_SCORE_RULES}

${buildMaxSaraGoldStandardPromptBlock()}
${validationBlock}

Score honestly from 0 to 10 (one decimal allowed).

Score these dimensions (0–10 each):
- hook: animated show opening — live mini-scene + short lively turns + vivid detail before topic reveal; warm branded welcome; emotional why-it-matters; concrete stay-promise; ~250–450 spoken words before [LESSON]; first 90s entertaining as podcast audio, not a lesson objective (maps: hookAndPromise)
- architecture: exact spine [INTRO]→[LESSON]→[PART N - TITLE]→[CLOSING]→thanks→[FINAL], continuous PART progression, [FINAL] last after [MAX] thank-you + [SARA] hope line, no music cues (maps: conversationalProgression)
- conversation: uniqueMechanism organizes discovery; stories, metaphor/model, counterpoint, emotional progression; not tip-list or drill (maps: storySpecificity + metaphorClarity + emotionalProgression)
- dialogue: Max and Sara distinct personalities; equal co-hosts; friction/reframe; short turns; natural reactions; no permanent teacher (maps: hostChemistry + naturalDialogue)
- catchUp: flexible natural catch-up (~4–12 turns when useful) or cold-open-as-catch-up that seeds the topic without lesson setup
- vocabularyChunks: phrases appear before Word Tour, recur naturally, stretch language explained in context; exactly one Word Tour payoff — not dictionary list (maps: lexicalIntegration + lexicalRecurrence + comprehensibleStretch)
- level: A2–B1 speakable core with careful stretch; concrete→abstract→concrete; comprehensible input
- completeness: hook, mechanism, both hosts' stories, metaphor, counterpoint, organic phrases, Word Tour, recap, comment question, goodbye (~3500–4400 spoken words, ~8–11 PARTs) (maps: closingPayoff + repetitionControl)

Score caps (apply the lowest relevant cap as a ceiling on overall score):
- short script / far below soft word floor → overall score ≤ 7.5
- includes Listen and Repeat / Your Turn / Quiz / Mission / learner pauses / Emma / Leo → overall score ≤ 6.5
- cold open is only a topic label with no tension/story/curiosity → overall score ≤ 7.8
- both hosts always agree / “Exactly” after nearly every turn / interchangeable voices → overall score ≤ 7.8
- no meaningful personal story from Max or Sara / only generic examples → overall score ≤ 7.8
- abstract philosophy for long stretches without ordinary examples → overall score ≤ 7.8
- vocabulary appears only in the Word Tour / never earlier → overall score ≤ 7.5
- vocabulary section reads like a dictionary list / "today we will study vocabulary" / "repeat these phrases" → overall score ≤ 7.8
- more than one late PART mainly listing/explaining the same phrases (duplicate phrase-collection) → overall score ≤ 8.0
- closing recap re-teaches the full phrase list after a phrase-collection section → overall score ≤ 8.2
- last third feels like repeated recap instead of natural conversation → overall score ≤ 8.2
- one host acts as permanent teacher or episode sounds like a formal lesson → overall score ≤ 7.8
- uniqueMechanism never becomes clear in the conversation → overall score ≤ 7.8
- missing comment question or vocabulary/chunks section → overall score ≤ 8.2
- any spine/FINAL/music/wrong-cast validation errors → overall score ≤ 8.0

Do NOT pass a script only because structure and word count are correct if the dialogue is flat.

Do NOT penalize merely because a vocabulary/chunks section exists — that section is required; only penalize classroom/list framing, missing earlier exposure, or duplicated phrase-collection sections.

Reply with ONLY valid JSON (no markdown fences, no extra text):
{"score": 8.4, "briefReason": "one short sentence naming the main weakness or strength", "dimensionScores": {"hook": 8.0, "architecture": 8.5, "conversation": 8.0, "dialogue": 8.0, "catchUp": 8.0, "vocabularyChunks": 7.5, "level": 8.5, "completeness": 8.0}, "strengths": ["..."], "mustFix": ["concrete fix 1", "concrete fix 2"], "rewritePriority": ["highest-leverage rewrite move first", "..."]}

Do not include, quote, summarize, or reproduce the script itself in the response.`;
  }

  return `You are scoring a Podcast English Lessons script (two-speaker Emma/Leo lesson).

${PRECEDING_ASSISTANT_SCRIPT_SCORE_RULES}

${buildPodcastGoldStandardPromptBlock()}
${validationBlock}

Score honestly from 0 to 10 (one decimal allowed). Do NOT artificially limit early drafts to 9.2 or below — if the draft is excellent, score it excellent.

Score these dimensions (0–10 each):
- hook: cold-open curiosity and episode promise
- architecture: exact spine [INTRO]→[LESSON]→[PART N - TITLE]→[CLOSING]→thanks→[FINAL], [FINAL] last after [LEO] thank-you + [EMMA] hope line, no music cues
- practice: complete conversation + Listen and Repeat + Your Turn + Build Your Own + Quick Speaking Quiz + Today's Mission
- dialogue: Emma teaches/models/corrects; Leo asks, errs, reacts, jokes — Leo does not mechanically echo Emma
- repetitionRhythm: Listen (no pause) vs Listen and Repeat (Emma once → pause, Leo does not echo) vs Your Turn / Build Your Own timing
- level: A1–B1 speakability and clarity
- completeness: gold-standard depth (~2800–3300 spoken words, ~11–13 PARTs, 18–22 min at speed 0.9)

Score caps (apply the lowest relevant cap as a ceiling on overall score):
- short script / far below word or PART targets → overall score ≤ 7.5
- missing complete conversation or missing practice system → overall score ≤ 7.8
- mechanical Emma→Leo identical echoes → overall score ≤ 7.5
- generic hook with no episode-specific comedy/conflict → overall score ≤ 8.2
- any spine/FINAL/music validation errors → overall score ≤ 8.0

Reply with ONLY valid JSON (no markdown fences, no extra text):
{"score": 8.4, "briefReason": "one short sentence naming the main weakness or strength", "dimensionScores": {"hook": 8.0, "architecture": 8.5, "practice": 7.5, "dialogue": 8.0, "repetitionRhythm": 7.0, "level": 8.5, "completeness": 7.5}, "strengths": ["..."], "mustFix": ["concrete fix 1", "concrete fix 2"], "rewritePriority": ["highest-leverage rewrite move first", "..."]}

Do not include, quote, summarize, or reproduce the script itself in the response.`;
}

export type ScriptWriterRevisionDecision =
  | "pass"
  | "polish"
  | "rewrite"
  | "regenerate";

export function normalizeScriptWriterRevisionDecision(
  value: unknown,
): ScriptWriterRevisionDecision | null {
  if (typeof value !== "string") {
    return null;
  }
  const normalized = value.trim().toLowerCase();
  if (
    normalized === "pass" ||
    normalized === "polish" ||
    normalized === "rewrite" ||
    normalized === "regenerate"
  ) {
    return normalized;
  }
  return null;
}

/**
 * Prefer the scorer's `decision`. Fall back to score bands when missing.
 * Ignore an inconsistent `pass` when the numeric score is still ≤ threshold.
 */
export function resolveScriptWriterRevisionDecision({
  decision,
  score,
  channelKey,
}: {
  decision?: unknown;
  score: number | null;
  channelKey?: string | null;
}): ScriptWriterRevisionDecision {
  const fromField = normalizeScriptWriterRevisionDecision(decision);
  if (fromField) {
    if (
      fromField === "pass" &&
      shouldRequestScriptRevision(score, channelKey)
    ) {
      // Scorer said pass but score is still ≤ threshold — use bands instead.
    } else {
      return fromField;
    }
  }

  if (channelKey === "wealth-insights") {
    if (score == null || !Number.isFinite(score)) {
      return "regenerate";
    }
    const passScore = getScriptWriterPassScore(channelKey);
    // Pass requires strictly above SCRIPT_WRITER_PASS_SCORE (9.2).
    if (score > passScore) {
      return "pass";
    }
    if (score >= 8.0) {
      return "polish";
    }
    if (score >= 7.0) {
      return "rewrite";
    }
    return "regenerate";
  }

  if (!shouldRequestScriptRevision(score, channelKey)) {
    return "pass";
  }
  return "rewrite";
}

/** Minimum score gain that resets the stalled-polish counter. */
export const SCRIPT_WRITER_POLISH_GAIN_MIN = 0.3;

/**
 * After two consecutive polish outcomes without enough score gain, escalate
 * to rewrite so the loop does not burn drafts on tiny edits.
 */
export function escalateStalledPolishDecision({
  decision,
  score,
  previousScore,
  stalledPolishCount,
  stallLimit = 2,
  minGain = SCRIPT_WRITER_POLISH_GAIN_MIN,
}: {
  decision: ScriptWriterRevisionDecision;
  score: number | null;
  previousScore: number | null;
  stalledPolishCount: number;
  stallLimit?: number;
  minGain?: number;
}): {
  decision: ScriptWriterRevisionDecision;
  stalledPolishCount: number;
  escalated: boolean;
} {
  if (decision !== "polish") {
    return { decision, stalledPolishCount: 0, escalated: false };
  }

  let nextStalled = stalledPolishCount;
  if (
    previousScore != null &&
    score != null &&
    Number.isFinite(previousScore) &&
    Number.isFinite(score)
  ) {
    const gain = score - previousScore;
    nextStalled = gain >= minGain ? 0 : stalledPolishCount + 1;
  }

  if (nextStalled >= stallLimit) {
    return {
      decision: "rewrite",
      stalledPolishCount: nextStalled,
      escalated: true,
    };
  }

  return {
    decision: "polish",
    stalledPolishCount: nextStalled,
    escalated: false,
  };
}

export function shouldReviseScriptForDecision(
  decision: ScriptWriterRevisionDecision,
) {
  return (
    decision === "polish" ||
    decision === "rewrite" ||
    decision === "regenerate"
  );
}

export type ScriptWriterBestDraft = {
  draftNumber: number;
  script: string;
  score: number;
  briefReason: string | null;
  mustFix: string[];
  rewritePriority: string[];
  dimensionScores: Record<string, number> | null;
};

/**
 * Keep the highest-scoring draft. Ties keep the earlier draft (stability).
 * A lower score is a regression and must not replace the best draft.
 */
export function considerScriptWriterBestDraft(
  best: ScriptWriterBestDraft | null,
  candidate: {
    draftNumber: number;
    script: string;
    score: number | null;
    briefReason: string | null;
    mustFix?: string[] | null;
    rewritePriority?: string[] | null;
    dimensionScores?: Record<string, number> | null;
  },
): {
  best: ScriptWriterBestDraft | null;
  accepted: boolean;
  rejectedAsRegression: boolean;
} {
  const script = candidate.script.trim();
  const score = candidate.score;
  if (!script || score == null || !Number.isFinite(score)) {
    return { best, accepted: false, rejectedAsRegression: false };
  }

  const next: ScriptWriterBestDraft = {
    draftNumber: candidate.draftNumber,
    script,
    score,
    briefReason: candidate.briefReason,
    mustFix: candidate.mustFix?.filter(Boolean) ?? [],
    rewritePriority: candidate.rewritePriority?.filter(Boolean) ?? [],
    dimensionScores: candidate.dimensionScores ?? null,
  };

  if (!best) {
    return {
      best: next,
      accepted: true,
      rejectedAsRegression: false,
    };
  }

  if (score > best.score) {
    return {
      best: next,
      accepted: true,
      rejectedAsRegression: false,
    };
  }

  // Equal score: keep earlier best. Lower score: reject regression.
  if (score === best.score) {
    return { best, accepted: true, rejectedAsRegression: false };
  }

  return { best, accepted: false, rejectedAsRegression: true };
}

/** Stop burning drafts after this many consecutive rejected revisions. */
export const SCRIPT_WRITER_MAX_CONSECUTIVE_REGRESSIONS = 2;

export function buildWealthPolishDepthRules(
  decision: ScriptWriterRevisionDecision | null | undefined,
) {
  if (decision === "polish") {
    return [
      "## Polish depth lock (mandatory for decision=polish)",
      "",
      "This is a surgical polish, not a rewrite.",
      "- Change ONLY what mustFix / rewritePriority require.",
      "- Preserve strong lines, scenes, metaphors, transitions, and pacing that already work.",
      "- Do NOT restructure the whole script.",
      "- Do NOT apply broad anti-repetition cuts unless mustFix explicitly requires them.",
      "- Do NOT delay/rebuild the thesis unless mustFix explicitly requires it.",
      "- Do NOT merge paragraphs unless mustFix explicitly requires it.",
      "- If unsure whether a change helps, keep the previous wording.",
      "- The revised draft must not be weaker overall than the previous script.",
    ].join("\n");
  }

  if (decision === "rewrite" || decision === "regenerate") {
    return [
      "## Structural revision checklist (decision=" + decision + ")",
      "",
      "- Anti-repetition: state the central mechanism once clearly, then advance with new facts, decisions, consequences, examples, or revelations.",
      "- Delay the full thesis when the opening currently spoils the chain too early.",
      "- Title payoff: if the workingTitle uses a vs / comparison frame, include concrete comparison beats.",
      "- Escalation: when costs or consequences stack, show clear progression.",
      "- Merge paragraphs that perform the same narrative function.",
      "- Still preserve strong material that does not contribute to scored weaknesses.",
      "- The revised draft should improve the scored weaknesses without discarding what already works.",
    ].join("\n");
  }

  return null;
}

export async function buildScriptWriterRevisionPrompt({
  draftNumber,
  score,
  briefReason,
  channelKey,
  script,
  mustFix,
  rewritePriority,
  validationReport,
  dimensionScores,
  projectBible,
  currentIdeaJson,
  episodeContext,
  decision,
}: {
  draftNumber: number;
  score: number | null;
  briefReason?: string | null;
  channelKey?: string | null;
  script?: string | null;
  mustFix?: string[] | null;
  rewritePriority?: string[] | null;
  validationReport?: string | null;
  dimensionScores?: Record<string, number> | null;
  projectBible?: string | null;
  currentIdeaJson?: unknown;
  episodeContext?: ScriptWriterEpisodeContext | null;
  decision?: ScriptWriterRevisionDecision | null;
}) {
  const channel = channelKey ? getChannelProfile(channelKey) : null;
  const revisionMarkdown = await readOptionalPromptMarkdown(
    channel?.prompts.scriptWriterRevision,
  );

  if (channelKey === "wealth-insights") {
    // Short same-chat revision: no Project Bible / Idea JSON / previous script
    // re-attach (those live in the thread). Stays under the file-upload threshold.
    const mustFixItems = mustFix?.filter(Boolean) ?? [];
    const priorityItems = rewritePriority?.filter(Boolean) ?? [];
    const scoreLabel =
      typeof score === "number" && Number.isFinite(score)
        ? score.toFixed(1)
        : "n/a";
    const reason = briefReason?.trim() || "";
    const mustFixBlock =
      mustFixItems.length > 0
        ? `\nMust fix:\n${mustFixItems.map((item, i) => `${i + 1}. ${item}`).join("\n")}`
        : "";
    const priorityBlock =
      priorityItems.length > 0
        ? `\nHighest-impact improvements:\n${priorityItems
            .map((item, i) => `${i + 1}. ${item}`)
            .join("\n")}`
        : "";
    const decisionLine = decision
      ? `\nRevision depth hint: ${decision} (prefer targeted improvements; keep what already works).`
      : "";

    return `Revise the Wealth Insights narration script from your previous assistant message (the draft we just scored).

Apply the critique below and any improvements you judge useful. Keep strong lines and the original mechanism. Return only the complete revised narration script — no JSON, no title, no score, no preamble, no notes, no markdown fences.

Score: ${scoreLabel}${decisionLine}
${reason ? `Brief reason: ${reason}` : ""}${mustFixBlock}${priorityBlock}

Do not mention the score, critique, or revision process in the narration.`;
  }

  if (channelKey !== PODCAST_ENGLISH_LESSONS_CHANNEL_KEY) {
    return revisionMarkdown ?? GENERIC_SCRIPT_WRITER_REVISION_PROMPT;
  }

  const nextDraft = draftNumber + 1;
  const passScore = getScriptWriterPassScore(channelKey);
  const scoreLabel =
    typeof score === "number" && Number.isFinite(score)
      ? score.toFixed(1)
      : "below the bar";
  const trimmedReason = briefReason?.trim() || "";
  const critiqueJson = JSON.stringify(
    {
      score: typeof score === "number" && Number.isFinite(score) ? score : null,
      briefReason: trimmedReason || null,
      dimensionScores: dimensionScores ?? null,
      mustFix: mustFix?.filter(Boolean) ?? [],
      rewritePriority: rewritePriority?.filter(Boolean) ?? [],
    },
    null,
    0,
  );
  const reasonLine = trimmedReason
    ? `ChatGPT critique to apply specifically:\n${trimmedReason}`
    : "Fix the weakest parts of the latest draft.";
  const mustFixBlock =
    mustFix && mustFix.length > 0
      ? `\nMUST FIX (address every item):\n${mustFix.map((item, i) => `${i + 1}. ${item}`).join("\n")}`
      : "";
  const priorityBlock =
    rewritePriority && rewritePriority.length > 0
      ? `\nREWRITE PRIORITY (highest leverage first):\n${rewritePriority.map((item, i) => `${i + 1}. ${item}`).join("\n")}`
      : "";
  const validationBlock = validationReport?.trim()
    ? `\nVALIDATION REPORT:\n${validationReport.trim()}`
    : "";
  const draftBlock = script?.trim()
    ? `

CURRENT DRAFT V${draftNumber} (revise this exact script; do not start from scratch):
\`\`\`
${script.trim()}
\`\`\`
`
    : "";

  const format = resolvePodcastFormatForCritique({
    validationReport,
    currentIdeaJson,
    episodeContext,
  });

  if (format === "max_sara_conversation") {
    return `Draft V${draftNumber} scored ${scoreLabel} (pass threshold is strictly above ${passScore.toFixed(1)}).
Critique JSON from the scorer: ${critiqueJson}
${reasonLine}${mustFixBlock}${priorityBlock}${validationBlock}
${draftBlock}
Rewrite a stronger V${nextDraft} of the FULL Max & Sara conversational podcast script.

${buildMaxSaraGoldStandardPromptBlock()}

Hard structure rules (must keep):
- Exact spine: [INTRO] → cold open → [LESSON] → sequential conversational [PART N - TITLE] blocks → [CLOSING] → recap / phrases / comment question → [MAX] thank-you → [SARA] hope line → [FINAL]
- [FINAL] must be the LAST label; immediately before it: [MAX] "Thank you for listening to Podcast English Lessons." then [SARA] hope line starting "We hope this conversation helped you feel understood and learn useful natural English for …"
- [MAX] / [SARA] alone on their own lines; dialogue underneath
- PART covers alone on their own lines; never append PART headings onto host dialogue
- Labels are not spoken and must not appear inside dialogue
- No music cues of any kind
- No Listen and Repeat, Your Turn, Quiz, Mission, learner pauses, Emma, Leo, or teacher/student dynamic
- Include a flexible natural catch-up (~4–12 turns when useful) that seeds the topic, or let the cold open itself be the catch-up
- Vocabulary/chunks must feel like an organic Word Tour payoff, not a dictionary list or “today we will study vocabulary”
- Important phrases should appear before the Word Tour and recur naturally
- Use only one explicit phrase-collection section; any later late-episode section should apply phrases in context, not re-list them
- Closing recap may mention 3–5 key phrases briefly — do not re-teach the full phrase section
- Include concrete stories from both hosts, a simple metaphor/model, and at least one mild counterpoint/reframe
- Acting tags whitelist only: [laughs], [sighs], [hungry], [confused], [nervous], [excited], [proud], [whispers]
- Expand via richer examples, stories, and natural dialogue — NEVER via drills or filler

Rules:
- Output ONLY the plain script text (bracket labels + dialogue)
- Do NOT wrap the script in JSON (no {"script":"..."}, no {"score":...})
- No title, no score, no preamble, no bullet notes, no markdown fences, no "V${nextDraft}" label
- Keep it speakable for A1–B1 voiceover
- Preserve the core conversation idea while executing mustFix + rewritePriority
- Never drop or rename the required bracket labels while revising`;
  }

  return `Draft V${draftNumber} scored ${scoreLabel} (pass threshold is strictly above ${passScore.toFixed(1)}).
Critique JSON from the scorer: ${critiqueJson}
${reasonLine}${mustFixBlock}${priorityBlock}${validationBlock}
${draftBlock}
Rewrite a stronger V${nextDraft} of the FULL Podcast English Lessons script.

${buildPodcastGoldStandardPromptBlock()}

Hard structure rules (must keep):
- Exact spine: [INTRO] → cold open → [LESSON] → sequential [PART N - TITLE] blocks → [CLOSING] → recap → [LEO] thank-you → [EMMA] hope line → [FINAL]
- [FINAL] must be the LAST label; immediately before it: [LEO] "Thank you for listening to Podcast English Lessons." then [EMMA] hope line starting "We hope this conversation helped you feel understood and learn useful natural English for …"
- [EMMA] / [LEO] alone on their own lines; dialogue underneath
- PART covers alone on their own lines; never append PART headings onto avatar dialogue
- Labels are not spoken and must not appear inside dialogue
- No music cues of any kind
- Acting tags whitelist only: [laughs], [sighs], [hungry], [confused], [nervous], [excited], [proud], [whispers]
- Listen and Repeat: Emma models once, then pause — Leo does NOT echo
- If you need more length/depth, expand via new situations, variants, real communication, role-play, and learner production — NEVER via mechanical echoes or filler

Rules:
- Output ONLY the plain script text (bracket labels + dialogue)
- Do NOT wrap the script in JSON (no {"script":"..."}, no {"score":...})
- No title, no score, no preamble, no bullet notes, no markdown fences, no "V${nextDraft}" label
- Keep it speakable for A1–B1 voiceover
- Preserve the core lesson idea while executing mustFix + rewritePriority
- Never drop or rename the required bracket labels while revising`;
}

export type ScriptScoreResult = {
  score: number | null;
  decision: ScriptWriterRevisionDecision | null;
  briefReason: string | null;
  dimensionScores: Record<string, number> | null;
  strengths: string[];
  mustFix: string[];
  rewritePriority: string[];
  rawText: string;
};

/**
 * Pull a complete {"score": …} object out of assistant text when present.
 */
export function extractEmbeddedScoreJson(text: string): string | null {
  const cleaned = stripChatGptUiChrome(text.trim());
  if (!cleaned || !/"score"\s*:/i.test(cleaned)) {
    return null;
  }

  const scoreObject = extractScoreJsonObject(cleaned);
  if (scoreObject) {
    return scoreObject;
  }

  const jsonText = extractJsonPayload(cleaned);
  if (!jsonText || !/"score"\s*:/i.test(jsonText)) {
    return null;
  }

  try {
    const parsed = JSON.parse(jsonText) as { score?: unknown };
    if (normalizeScore(parsed.score) == null) {
      return null;
    }
    return jsonText;
  } catch {
    return null;
  }
}

/**
 * True when assistant text looks like a finished critique/score reply
 * (used by ChatGPT waitForCompletion for short responses).
 */
export function looksLikeScriptScoreResponse(text: string): boolean {
  const cleaned = stripChatGptUiChrome(text.trim());
  if (!cleaned) {
    return false;
  }

  if (extractEmbeddedScoreJson(cleaned)) {
    return true;
  }

  if (cleaned.length > 1200) {
    return false;
  }

  if (
    /(?:score|rating|nota|puntuaci[oó]n)\s*[:=]?\s*\d{1,2}(?:[.,]\d)?\s*(?:\/\s*10)?/i.test(
      cleaned,
    )
  ) {
    return true;
  }

  if (/\b\d{1,2}(?:[.,]\d)?\s*\/\s*10\b/.test(cleaned)) {
    return true;
  }

  return false;
}

function asStringList(value: unknown): string[] {
  if (!Array.isArray(value)) {
    return [];
  }
  return value
    .map((item) => (typeof item === "string" ? item.trim() : ""))
    .filter(Boolean);
}

function asDimensionScores(value: unknown): Record<string, number> | null {
  if (!value || typeof value !== "object" || Array.isArray(value)) {
    return null;
  }
  const out: Record<string, number> = {};
  for (const [key, raw] of Object.entries(value as Record<string, unknown>)) {
    const score = normalizeScore(raw);
    if (score != null) {
      out[key] = score;
    }
  }
  return Object.keys(out).length > 0 ? out : null;
}

/**
 * Parse a ChatGPT critique reply into a numeric score (+ richer fields when present).
 */
export function extractScriptScore(rawResponse: string): ScriptScoreResult {
  const rawText = rawResponse.trim();
  const cleaned = stripChatGptUiChrome(rawText);
  if (!cleaned) {
    return {
      score: null,
      decision: null,
      briefReason: null,
      dimensionScores: null,
      strengths: [],
      mustFix: [],
      rewritePriority: [],
      rawText,
    };
  }

  const embedded = extractEmbeddedScoreJson(cleaned);
  const jsonText = embedded ?? extractJsonPayload(cleaned);
  if (jsonText) {
    try {
      const parsed = JSON.parse(jsonText) as {
        score?: unknown;
        overallScore?: unknown;
        decision?: unknown;
        briefReason?: unknown;
        reason?: unknown;
        mainWeakness?: unknown;
        mainStrength?: unknown;
        dimensionScores?: unknown;
        strengths?: unknown;
        mustFix?: unknown;
        rewritePriority?: unknown;
      };
      const score = normalizeScore(parsed.overallScore ?? parsed.score);
      const decision = normalizeScriptWriterRevisionDecision(parsed.decision);
      const briefReason =
        typeof parsed.briefReason === "string"
          ? parsed.briefReason.trim()
          : typeof parsed.reason === "string"
            ? parsed.reason.trim()
            : typeof parsed.mainWeakness === "string"
              ? parsed.mainWeakness.trim()
              : null;
      const strengths = asStringList(parsed.strengths);
      if (
        strengths.length === 0 &&
        typeof parsed.mainStrength === "string" &&
        parsed.mainStrength.trim()
      ) {
        strengths.push(parsed.mainStrength.trim());
      }
      if (score != null) {
        return {
          score,
          decision,
          briefReason: briefReason || null,
          dimensionScores: asDimensionScores(parsed.dimensionScores),
          strengths,
          mustFix: asStringList(parsed.mustFix),
          rewritePriority: asStringList(parsed.rewritePriority),
          rawText,
        };
      }
    } catch {
      // fall through to prose parsing
    }
  }

  const labeled = cleaned.match(
    /(?:score|rating|nota|puntuaci[oó]n)\s*[:=]?\s*(\d{1,2}(?:[.,]\d)?)\s*(?:\/\s*10)?/i,
  );
  if (labeled?.[1]) {
    return {
      score: normalizeScore(labeled[1].replace(",", ".")),
      decision: null,
      briefReason: extractProseReason(cleaned),
      dimensionScores: null,
      strengths: [],
      mustFix: [],
      rewritePriority: [],
      rawText,
    };
  }

  const outOfTen = cleaned.match(/\b(\d{1,2}(?:[.,]\d)?)\s*\/\s*10\b/);
  if (outOfTen?.[1]) {
    return {
      score: normalizeScore(outOfTen[1].replace(",", ".")),
      decision: null,
      briefReason: extractProseReason(cleaned),
      dimensionScores: null,
      strengths: [],
      mustFix: [],
      rewritePriority: [],
      rawText,
    };
  }

  const loneNumber = cleaned.match(
    /^[\s"'`]*(\d{1,2}(?:[.,]\d)?)[\s"'`*(/]*10?[\s)"'`]*$/,
  );
  if (loneNumber?.[1]) {
    return {
      score: normalizeScore(loneNumber[1].replace(",", ".")),
      decision: null,
      briefReason: null,
      dimensionScores: null,
      strengths: [],
      mustFix: [],
      rewritePriority: [],
      rawText,
    };
  }

  return {
    score: null,
    decision: null,
    briefReason: null,
    dimensionScores: null,
    strengths: [],
    mustFix: [],
    rewritePriority: [],
    rawText,
  };
}

function extractProseReason(cleaned: string): string | null {
  const afterDash = cleaned.match(
    /(?:score|rating|nota|puntuaci[oó]n)[^\n]{0,40}(?:—|-|:)\s*(.+)$/i,
  );
  const reason = afterDash?.[1]?.trim();
  if (!reason || reason.length < 8 || reason.length > 280) {
    return null;
  }
  return reason.replace(/^["'`]+|["'`]+$/g, "").trim() || null;
}

/** True when we should request another improved draft. */
export function shouldRequestScriptRevision(
  score: number | null,
  channelKey?: string | null,
) {
  if (score == null || !Number.isFinite(score)) {
    return true;
  }
  return score <= getScriptWriterPassScore(channelKey);
}

/** @deprecated Use shouldRequestScriptRevision */
export const shouldRequestScriptV2 = shouldRequestScriptRevision;

function normalizeScore(value: unknown): number | null {
  const numeric =
    typeof value === "number"
      ? value
      : typeof value === "string"
        ? Number(value.trim().replace(",", "."))
        : NaN;

  if (!Number.isFinite(numeric)) {
    return null;
  }

  if (numeric < 0 || numeric > 10) {
    return null;
  }

  return Math.round(numeric * 10) / 10;
}
