import type { ChatGptGenerationMode } from "@/lib/chatgpt-scene-handoff";
import { buildGodsWordImagePromptBodyContract } from "@/lib/the-gods-word-image-prompt";

// Re-export for callers that historically imported the lock from this module.
export { THE_GODS_WORD_STYLE_LOCK } from "@/lib/the-gods-word-image-prompt";

/**
 * TheGodsWord compact-flow Visual Brief used by the ChatGPT scene request generator.
 * Keep avatar/space/style guidance stable; insert + chapter-cover rules are the production focus.
 * Exact style/negative locks are app-owned and assembled after ChatGPT returns bodies.
 */
export function buildTheGodsWordFlowVisualBrief() {
  return [
    "## TheGodsWord Flow Visual Brief",
    "",
    "TheGodsWord is an English Christian reflective storytelling channel in an illustrated Bible-study explainer style.",
    "",
    "Visual style (guidance only — do NOT paste a style lock into imagePrompt):",
    "Hand-painted watercolor and ink Bible-study illustration; warm off-white paper; soft sketch outlines; muted earth tones; calm reverent mood.",
    "The app injects the exact production style lock and negatives after you return each imagePrompt body.",
    "",
    "Core rule:",
    "The assigned `scriptText` is the main director of the `imagePrompt` body.",
    "",
    "Meaning-first rule:",
    "The visual must represent the specific meaning of the assigned scriptText, not only the general topic of the video.",
    "",
    "Before choosing symbols, ask:",
    "- What is happening in this exact fragment?",
    "- Is this fragment describing a biblical action, a teaching claim, a contrast, a viewer application, a question, a correction, or a transition?",
    "- What would the viewer need to see to understand this specific line without relying only on the narration?",
    "",
    "Choose the visual type after understanding the meaning.",
    "Do not choose a beautiful symbol first and then force it onto the line.",
    "",
    "### Segmentation gate before scene-type choice",
    "",
    "Segmentation must happen before insert design and before choosing scene types or visual formats.",
    "When the script includes [HOOK]…[END HOOK], treat that block as the hook and segment it before the body.",
    "",
    "#### Global word-floor (hook + body + covers with spoken opener)",
    "",
    "- Never create a single-word scene anywhere in the video (e.g. \"So.\" alone is forbidden).",
    "- Never create a 1–3 word scene unless it is an exact short quotation, a deliberate word-study emphasis, or must pair immediately with an adjacent micro-beat in the same scene.",
    "- Prefer merging a tiny fragment with the neighboring clause of the same claim rather than emitting a 1–3 word scene.",
    "",
    "#### Hard hook segmentation (HOOK ONLY)",
    "",
    "Apply this subsection ONLY to [HOOK]…[END HOOK]. Do NOT apply Hard hook segmentation to CHAPTER / body / FINAL sections.",
    "",
    "A hook scene must represent one recognizable narrative beat (question, brief action, progression step, interruption, reaction, correction, consequence, or important emotional clause).",
    "",
    "Obligations:",
    "- Preserve every spoken word exactly once and in its original order.",
    "- Do not merge two rhetorical questions into one scene.",
    "- Do not merge a setup beat with its reversal or consequence.",
    "- Separate parallel actions when each one deserves an individual visual beat.",
    "- A short progression such as You read / You hear / You recognize should normally become separate consecutive scenes.",
    "- Split long hook sentences at natural clause boundaries when the clauses perform different narrative functions.",
    "- Never split in the middle of a noun phrase, phrasal verb, quotation, Bible reference, or indivisible idea.",
    "- Do not create a scene containing more than two short sentences.",
    "- Lists of four or more short interruptions must be divided into at least two scenes.",
    "- Two extremely short and closely related interruption beats may share one scene (and must, when needed, to avoid a 1–3 word orphan).",
    "- Do not merge independent hook beats merely to reach a preferred scene duration.",
    "",
    "Keep always in different scenes in the HOOK:",
    "- question and answer",
    "- statement and correction",
    "- action and consequence",
    "- expectation and twist",
    "- problem and thesis",
    "- outer experience and inner effect",
    "",
    "Hook length guidance:",
    "- Usually 4 to 12 narrated words per hook scene; soft max about 16 words.",
    "- Never emit a one-word hook scene.",
    "- A 2–3 word hook fragment must pair with an immediate parallel micro-beat or the next clause of the same beat.",
    "",
    "Hook silent check: `This scene exists to make the viewer immediately understand that ______.`; if the blank needs “and” for two independent claims, split again.",
    "",
    "#### Moderate body segmentation (CHAPTER / body / FINAL spoken sections)",
    "",
    "Body sections use meaning-first segmentation that is LESS aggressive than the hook.",
    "",
    "Body targets (authoritative for CHAPTER and other non-hook spoken sections):",
    "- Aim for about 15 to 25 narrated words per body scene.",
    "- Soft duration floor: about 5 to 6 seconds (prefer 6–8 seconds).",
    "- Soft duration ceiling: 8 seconds. Do not plan 9–11s body scenes.",
    "- Prefer merging two clauses of the SAME principal claim into one scene.",
    "- Split only when claims need different visuals (true contrast, question→answer, action→consequence, or a dense list of distinct actions).",
    "",
    "Body silent check (moderate):",
    "`This scene exists to make the viewer immediately understand that ______.`",
    "If the blank needs “and” only to join two sides of the same claim, KEEP one scene.",
    "If the blank needs “and” to join two independent claims that need different images, THEN split.",
    "",
    "A normal insert may still communicate only one principal narration claim — but a principal claim may span a short sentence pair when they teach the same point.",
    "",
    "If a narration fragment contains more visual information than one insert can communicate at scene speed:",
    "- split into consecutive scenes",
    "- preserve every word and exact order",
    "- do not duplicate or omit narration",
    "- do not solve overload with mini-panels, boards, icon rings, or tiny supporting illustrations",
    "",
    "When the fragment contains several distinct human actions, consider consecutive `avatar` scenes rather than forcing them into one insert.",
    "",
    "Dense-list split example (body or application lists):",
    "Original narration:",
    "Releasing the idol. Forgiving the enemy. Rejecting the compromise. Asking for help. Leaving the danger.",
    "",
    "Do not create one insert labeled RELEASE / REFUSE / SEEK.",
    "",
    "Instead split it naturally, for example:",
    "Scene A scriptText: Releasing the idol. Forgiving the enemy. Rejecting the compromise.",
    "Best visual: one simple insert with three large literal actions directly named in that text: an idolized trophy being laid down; a heavy stone of resentment being released; a corrupt offer being pushed away. No visible text.",
    "Scene B scriptText: Asking for help. Leaving the danger.",
    "Best visual: a present-day avatar scene with one person leaving an unsafe doorway and moving toward one clearly offered helping hand. No visible text.",
    "",
    "The narration must determine the split.",
    "",
    "### Script coverage lock",
    "",
    "Concatenating every scene.scriptText (normalizing only whitespace) must reproduce the spoken script for the processed section exactly.",
    "Detect and forbid omitted words, duplicated words, reordering, paraphrase, or invented narration.",
    "Structural markers such as [HOOK], [END HOOK], [CHAPTER…], [FINAL…], [INTRODUCTION], [CHAPTER COVER — …], [REFLECTION AND PRAYER], [CLOSING], and [CONCLUSION] are not spoken narration.",
    "",
    "### Structural labels never go in scriptText",
    "",
    "Labels mark segmentation and cover placement only.",
    "Never copy [HOOK], [END HOOK], [CHAPTER N - TITLE], [FINAL — TITLE], [INTRODUCTION], [CHAPTER COVER — …], [REFLECTION AND PRAYER], [CLOSING], or [CONCLUSION] into any scene scriptText.",
    "scriptText must contain only words that will be read in voiceover.",
    "When a label is followed by a spoken opener (title, chapter announcement, section start), that opener is the cover scene: same scriptText + cover visual.",
    "Do not create a silent empty cover and then put the opener in a later scene.",
    "Category-specific cover+voiceover rules (e.g. The Bible in One Year) override when present.",
    "",
    "### JSON safety (hard rule)",
    "",
    "Return strict valid JSON array only. No markdown fences. No commentary.",
    "Do not use unescaped double quotes inside string values.",
    "Prefer avoiding quotation marks in imagePrompt — write exact readable visible title: HE WAS HEARD not \"HE WAS HEARD\".",
    "If a double quote is unavoidable, escape it as \\\".",
    "Do not break JSON strings with raw newlines inside quotes.",
    "Invalid JSON (for example comment \"Day 1 complete\" without escaping) is a failed output.",
    "",
    "### Chapter-cover contract",
    "",
    "For FULL_VIDEO generation:",
    "- Every exact marker matching [CHAPTER N - TITLE] must create one chapter-cover insert (digits may be 1 or 01; dash may be - or —).",
    "- [FINAL — TITLE] must also create one final-cover insert.",
    "- [HOOK] does not create a cover.",
    "- The cover must be the first scene assigned to that section.",
    "- The chapter title must be taken exactly from the marker.",
    "- Do not add a subtitle.",
    "- Do not rewrite, shorten, or paraphrase the chapter title.",
    "- Use one central illustration only.",
    "- No diagram, labels, supporting panels, secondary quotation, or explanatory text.",
    "- These official chapter covers are exempt from the normal insert text limits.",
    "- Chapter covers must not influence the planner into making nearby normal inserts look like covers.",
    "",
    "Represent chapter covers using existing fields only (no new schema fields):",
    'sceneType: "insert"',
    "visualPurpose: state that it opens the exact chapter",
    "visualIdea: Chapter cover: [EXACT TITLE], with [one central visual]",
    "",
    "Do not output the chapter map.",
    "Do not add section fields to the JSON.",
    "",
    "Workflow:",
    "",
    "1. Understand the beat.",
    "2. Segment if it contains several beats.",
    "3. Choose the visual format that best communicates that beat.",
    "4. Review variety in the nearby sequence.",
    "5. Change format only if another option is equally faithful to the scriptText.",
    "",
    "- Stage that format as a concrete final still (app applies the watercolor lock).",
    "- Do not default to generic skies, paths, lamps, or atmosphere when a concrete object, person, or place fits better.",
    "",
    "### visualIdea format prefixes (required)",
    "",
    "Every visualIdea MUST begin with exactly one of these prefixes (no new JSON fields):",
    "- Narrative scene:",
    "- Object/detail insert:",
    "- Chapter cover:",
    "- Concept card:",
    "- Scripture/reference card:",
    "- Comparison card:",
    "- Simple diagram:",
    "- Question card:",
    "- Word-study card:",
    "- Atmosphere/space:",
    "",
    "Examples:",
    "Concept card: Information is not transformation, centered above one seed resting on unopened soil.",
    "Question card: Did you give it somewhere to land?, with one seed suspended above a crowded stone path.",
    "Object/detail insert: One phone lighting beside an open Bible while a loose seed remains on the page.",
    "",
    "Visual format:",
    "For each scene, before writing the imagePrompt, choose the best visual format. Encode it with the visualIdea prefix above.",
    "",
    "1. `narrative scene` — biblical person, event, place, action, or moment.",
    "2. `object/detail insert` — close object or detail carries the line.",
    "3. `chapter cover` — exact chapter title from marker, one central illustration; opens that chapter.",
    "4. `concept card` — core idea, thesis, or memorable phrase with exact short visible text.",
    "5. `scripture/reference card` — Scripture quote or Bible reference with exact short visible text.",
    "6. `comparison card` — one compact contrast with two clear sides.",
    "7. `simple diagram` — rare; only when the script explicitly needs a single process relationship within complexity limits.",
    "8. `question card` — exact reflective question when the question itself is the beat.",
    "9. `word-study card` — exact word or short phrase when the narration pauses on that word.",
    "10. `atmosphere / space` — concrete place, pause, transition, road, room, landscape, or silence tied to the scriptText.",
    "",
    "### Positive insert-format triggers",
    "",
    "Semantic alignment with scriptText remains the first priority. Use these positive triggers so cards are not systematically avoided:",
    "",
    "Object/detail insert — use when:",
    "- a concrete object can confirm the beat immediately",
    "- the action is understood without text",
    "- there is one visual focus",
    "- the object is named or clearly implied in the fragment",
    "Do not make this the automatic format for every concept.",
    "",
    "Concept card — use when:",
    "- the script states a brief memorable thesis",
    "- the exact phrase is stronger than a generic metaphor",
    "- a literal illustration would reduce or trivialize the meaning",
    "- the text can be read quickly",
    "- the previous scenes were not consecutive text cards",
    "Candidate phrases (examples only): Information is not transformation. / The problem is not the seed. / The invitation is: Return.",
    "Visible text must come from scriptText. Never invent new slogans.",
    "",
    "Question card — use when:",
    "- the script asks the viewer a direct question",
    "- the question is a turn, personal exam, or section opener",
    "- keeping the exact question has more impact than a person thinking",
    "- the text length is readable",
    "Do not convert every question into a card. Alternate with human or symbolic scenes.",
    "",
    "Comparison card — use when:",
    "- the fragment contains an explicit contrast",
    "- both sides are clearer shown together",
    "- the contrast can be two clear sides",
    "- it does not need several secondary explanations",
    "Examples: Information / Transformation. Hearing / Receiving. More truth / More time.",
    "Use only exact words from the assigned fragment.",
    "",
    "Scripture/reference card — use when:",
    "- the fragment includes a Bible quotation",
    "- it includes a reference",
    "- a saying of Jesus must be kept verbatim",
    "- the exact text is already present in scriptText",
    "Do not invent quotations from memory.",
    "",
    "Word-study card — use when:",
    "- one exact word is central to the argument",
    "- narration pauses on that word",
    "- showing it helps fix the concept",
    "- it does not require a long definition",
    "",
    "Simple diagram — keep rare. Use only when the script explicitly presents a relationship, a progression, a process of up to three stages, or a sequential transformation. Never diagram a paragraph summary.",
    "",
    "### Insert taxonomy",
    "",
    "All chapter covers are inserts, but not all inserts should look like chapter covers.",
    "",
    "Only official chapter-cover scenes may use:",
    "- large chapter-style title taken exactly from the marker",
    "- clean cover-like layout",
    "- one central emblem designed like a chapter card",
    "",
    "Chapter covers have no subtitle.",
    "",
    "### Normal insert production contract",
    "",
    "Core insert rule:",
    "A normal insert is a fast visual confirmation of one narration beat.",
    "",
    "It is not:",
    "- a paragraph summary",
    "- a teaching slide",
    "- a miniature infographic",
    "- a collection of several application examples",
    "- a place to introduce concepts from later narration",
    "",
    "Every normal insert must use:",
    "- one dominant composition",
    "- one principal claim",
    "- one to three large visual elements",
    "- four large elements only when the exact narration explicitly gives four closely related items and the duration is at least 10 seconds",
    "- no miniature scenes",
    "- no comic-strip panels",
    "- no tiny secondary illustrations",
    "- no secondary explanatory layer",
    "- no visual homework",
    "",
    "The viewer should understand the basic relationship in one glance while continuing to listen.",
    "",
    "Direct script alignment:",
    "Every object, action, contrast, and visible word must come directly from the assigned `scriptText`.",
    "",
    "Do not:",
    "- invent umbrella labels",
    "- replace the narration with approximate synonyms",
    "- introduce a conclusion from the next sentence",
    "- choose symbols merely because they belong to the general topic",
    "- use theological shorthand that the narration has not yet established",
    "",
    "One-claim rule:",
    "Before writing `visualIdea`, silently complete this sentence:",
    "This insert exists to make the viewer immediately understand that ______.",
    "",
    "The blank must contain only one claim from the current `scriptText`.",
    "If the answer contains and, inspect whether the fragment needs to be split.",
    "",
    "`visualPurpose` must state that one claim.",
    "`visualIdea` must be a concrete drawable composition, not a meta-instruction.",
    "",
    "Bad visualIdea:",
    "- Direct literal summary of the scriptText",
    "- A board explaining the narration",
    "- Choose representative elements from the fragment",
    "- A visual showing the main ideas",
    "",
    "Good visualIdea:",
    "- One rough Roman crossbeam, one iron nail, and the shadow of a Roman guard",
    "- A promotion badge resting over the dishonest document used to obtain it",
    "- Closed hands guarding a glowing life-token as it fades between the fingers",
    "",
    "### Complexity budget by duration",
    "",
    "Apply these limits to normal inserts.",
    "",
    "Hook duration guidance (integer seconds; narration beats win over padding):",
    "- 3 seconds for very brief micro-beats",
    "- 4 seconds for questions and short actions",
    "- 5 seconds for emotional beats",
    "- 6 seconds only for an exceptionally dense clause",
    "- Never a one-word scene; merge 1–3 word orphans with the neighbor when possible",
    "- Do not merge independent hook beats only to justify a longer duration",
    "",
    "Body duration guidance (CHAPTER / body):",
    "- Soft floor 5–6 seconds; prefer 6–8 seconds; soft ceiling 8 seconds",
    "- Target about 15–25 narrated words per body scene",
    "",
    "3–6 seconds (mostly hook):",
    "- one focal object or action",
    "- up to three large elements",
    "- no panels",
    "- no process with several stages",
    "- prefer format-specific visible-text budgets below",
    "",
    "5–8 seconds (body default):",
    "- one focal relationship",
    "- or one two-sided contrast",
    "- or up to three matched elements when the script names them",
    "- do not use extra seconds as permission to summarize a whole paragraph",
    "",
    "### Visible-text policy (per format)",
    "",
    "Default for object/detail and direct symbolic action: No visible text.",
    "",
    "The planner must explicitly decide whether an insert uses text.",
    "Do not write ambiguous instructions such as:",
    "- use text if needed",
    "- optionally show",
    "- Flow may choose",
    "- if the image reads clearly",
    "",
    "Every insert imagePrompt body must state one of these:",
    "- No visible text, captions, letters, or words.",
    "- Use only this exact visible text: [TEXT]. No other words.",
    "For avatar / space: do not write those lines — the app appends no-text + negatives.",
    "",
    "Visible-text budgets (visible words only — not scriptText length):",
    "- Object/detail insert: no text by default; max 4 words when indispensable",
    "- Direct symbolic action: no text by default",
    "- Comparison card: max 8 visible words total",
    "- Concept card: one exact phrase up to 8 words",
    "- Question card: one exact question up to 12 words",
    "- Scripture/reference card: exact excerpt up to 10 words plus the reference",
    "- Word-study card: one exact word or phrase up to 4 words",
    "- Chapter cover: keep current rules; exact full title allowed",
    "",
    "The text must be:",
    "- exact wording from the current scriptText",
    "- the exact current question",
    "- an exact command",
    "- an exact contrast already stated in the fragment",
    "",
    "Do not invent summary vocabulary.",
    "",
    "Negation/correction rule:",
    "Never extract a rejected or negated phrase as the visible text.",
    "When a fragment contains a false statement followed by a correction, the visual must emphasize the correction.",
    "",
    "Example:",
    "Narration: Jesus does not say: Destroy yourself. He says: Follow Me.",
    "Wrong visible text: DESTROY YOURSELF",
    "Correct visible text: FOLLOW ME",
    "",
    "Example:",
    "Narration: Do not ask only: Is this painful? Ask: Is Jesus leading me here?",
    "Wrong visible text: IS THIS PAINFUL?",
    "Correct visible text: IS JESUS LEADING?",
    "",
    "Chapter covers are the only exception to the normal title-length limits.",
    "",
    "### Insert format decision order",
    "",
    "After segmentation, choose among these when the trigger fits:",
    "1. object/detail insert with no text, when a named/implied object confirms the beat",
    "2. direct symbolic action with no text",
    "3. concept / question / comparison / word-study / scripture card when the positive trigger above fits",
    "4. simple diagram only for an explicit short process",
    "5. narrative avatar or concrete space when a person, place, or pause is clearer",
    "",
    "Do not default to:",
    "- devotional visual boards",
    "- overloaded comparison boards",
    "- paragraph diagrams",
    "- converting every insert into a card",
    "- converting every hook beat into a card",
    "",
    "A board or diagram should be rare and must pass all complexity limits.",
    "A normal board must still behave like one fast insert, not a presentation slide.",
    "",
    "Do not use guidance that encourages:",
    "- tiny secondary illustrations around a main figure",
    "- several side-by-side examples",
    "- multi-panel before-and-after layouts",
    "- cause/effect layouts containing many secondary details",
    "",
    "### Soft insert-format balance",
    "",
    "Variety is a later check, never the first reason to choose a scene.",
    "",
    "- Do not use more than three consecutive object/detail inserts when another semantically valid format exists.",
    "- In any window of eight normal inserts, try to use at least three distinct visual formats when the script allows.",
    "- For full-video plans, aim roughly 15% to 25% of normal inserts toward concept, question, comparison, word-study, or scripture cards when exact text exists.",
    "- Never force a card when no exact suitable text exists.",
    "- No more than two text-based inserts consecutively.",
    "- Chapter covers do not count toward the consecutive-text limit.",
    "- Avoid repeating the exact same visual construction with only minor object swaps.",
    "",
    "Scene types:",
    "",
    "- `avatar`: use when Jesus, disciples, angels, biblical people, ordinary believers, viewer stand-ins, or human emotion are central to the narration.",
    "- For viewer application lines, `avatar` often means contemporary believers or anonymous viewer stand-ins, not biblical characters.",
    "- Use this especially when the narration is about how we respond, what we expect, how we misunderstand, our disappointment, confusion, hope, or personal application.",
    "- `insert`: use for chapter covers, object details, symbolic close-ups, and text cards when a positive trigger fits.",
    "- `space`: use for concrete places, transitions, silence, pauses, roads, rooms, landscapes, or visual breathing room that still directly match the assigned scriptText.",
    "",
    "Hard sceneType lock:",
    'Every scene.sceneType must be exactly one of: "avatar", "insert", "space".',
    "Do not invent other sceneType values.",
    "Do not output character, host, person, object, card, closeup, broll, landscape, establishing, environment, transition, atmosphere, graphic, or symbol as sceneType.",
    "If unsure, choose the closest allowed type (people/emotion → avatar; object/detail/cover → insert; place/pause/transition → space).",
    "",
    "### Scene-type correction rule",
    "",
    "Do not force a fragment to remain an insert.",
    "",
    "Use `avatar` instead when:",
    "- the narration describes a human decision",
    "- several listed items are better represented by one recognizable human action",
    "- viewer identification is more important than conceptual compression",
    "- emotion, resistance, confession, fear, forgiveness, asking for help, or leaving danger is central",
    "",
    "Use `space` when the fragment genuinely needs a concrete pause or physical transition.",
    "",
    "This change must not weaken the existing avatar or space guidance.",
    "",
    "Space does not mean abstract symbolism.",
    "Space does not mean generic sky, generic road, generic lamp, generic parchment, or decorative religious objects.",
    "",
    "A good space scene should answer:",
    "- Where are we in this exact narration?",
    "- What pause, transition, or emotional beat is being shown?",
    "- How does this place or silence relate to the scriptText?",
    "",
    "Examples of good space usage:",
    "- a quiet first-century street after a healed person leaves, if the narration describes Jesus no longer entering towns openly",
    "- a Galilean road as Jesus and the disciples move toward a question",
    "- a quiet present-day Bible-study room when the narration says the idea feels backwards to someone raised to speak about Jesus",
    "- an empty synagogue after a tense confrontation, if the narration has just described that setting",
    "- a narrow road toward Jerusalem when the narration says the story is moving toward suffering",
    "",
    "Weak space:",
    "- religious objects arranged beautifully but not tied to the line",
    "- a generic open Bible for every reflective sentence",
    "- a random crown, lamp, scroll, cup, or cross-shadow when the line is about a person, question, or action",
    "",
    "Do not let `insert` become the default scene type only because cards and boards exist.",
    "",
    "Soft distribution guidance for full Bible-study explainer videos:",
    "Do not force exact percentages, but avoid extreme imbalance.",
    "",
    "A strong full-video plan often lands near:",
    "- avatar: 30 to 40 percent",
    "- insert: 35 to 50 percent",
    "- space: 10 to 25 percent",
    "",
    "Semantic alignment overrides distribution.",
    "If a viewer-application line needs a person, use avatar.",
    "If one claim needs a fast visual confirmation, use insert.",
    "If the narration needs a concrete pause or transition, use space.",
    "",
    "Visual rhythm:",
    "Across a full plan, mix formats intentionally:",
    "- chapter covers for every [CHAPTER N - TITLE] and [FINAL — TITLE]",
    "- narrative scenes for biblical moments",
    "- object/detail inserts for memorable symbols named or implied by the line",
    "- concept / question / comparison / word-study / scripture cards when their positive triggers fit",
    "- space scenes only for concrete breath, transition, or place-setting tied to the line",
    "",
    "Meaningful visual variety:",
    "Vary the visual format without drifting away from the narration.",
    "",
    "Good variety means:",
    "- the same idea is not repeated with the same composition",
    "- repeated motifs evolve as the argument develops",
    "- scene type changes serve the scriptText",
    "- each image feels like a new step in the explanation",
    "",
    "Bad variety means:",
    "- using unrelated symbols just to avoid repetition",
    "- replacing a concrete human moment with abstract objects",
    "- making many inserts look like covers",
    "- using space scenes as decorative filler",
    "",
    "Repeat motifs when useful, but do not repeat the same prompt structure.",
    "No imagePrompt should be exactly duplicated.",
    "",
    "Insert variety must never override semantic simplicity.",
    "No more than two text-based inserts consecutively.",
    "Chapter covers do not count toward this consecutive-text limit.",
    "",
    "Narrative anchoring:",
    "When a reflective or theological fragment is still talking about a biblical moment, keep the image anchored in that biblical moment. Do not jump to a generic devotional metaphor too early.",
    "",
    "Semantic visual alignment:",
    "Choosing the right format is not enough. The image must visually explain what the assigned scriptText actually says.",
    "",
    "Every scene must pass this test:",
    "",
    "1. Literal or narrative match:",
    "   If scriptText describes an action, event, person, place, or moment, show that moment clearly.",
    "",
    "2. Teaching claim match:",
    "   If scriptText explains an idea, show the single relationship, contrast, process, or misunderstanding being taught.",
    "",
    "3. Viewer application match:",
    "   If scriptText speaks to we, our, us, you, your, or a modern reader, show a contemporary or timeless-contemporary human situation that reflects the line.",
    "",
    "4. Transition match:",
    "   If scriptText pauses, shifts, or invites the viewer to think, use a concrete setting that reflects that pause, not unrelated religious objects.",
    "",
    "5. Symbol match:",
    "   If using a symbol, the symbol must be named, clearly implied, or directly useful for explaining the exact scriptText.",
    "",
    "Avoid symbolic-adjacent prompts:",
    "Do not create scenes that are only beautiful, atmospheric, devotional, or generally related to the topic.",
    "A crown, cup, scroll, lamp, road, sky, garden, cross, seed, or open Bible is not enough unless it directly explains the assigned scriptText.",
    "",
    "Prefer understandable scenes over elegant abstractions.",
    "",
    "### Required insert examples",
    "",
    "Example A — simple object insert:",
    "Narration: It was an instrument of execution.",
    "Good: one rough crossbeam; one iron nail; one Roman guard shadow; no text.",
    "Bad: execution notice; several weapons; a city scene; labels explaining Rome and crucifixion.",
    "",
    "Example B — exact three-part sequence:",
    "Narration: Deny yourself. Take up your cross. Follow Me.",
    "Good: lowered crown; hands lifting a crossbeam; footprints behind Jesus; visible text: DENY / TAKE / FOLLOW.",
    "Bad: a long subtitle; explanatory definitions under every command; several mini-scenes.",
    "",
    "Example C — correction after a negation:",
    "Narration: Jesus does not say: Destroy yourself. He says: Follow Me.",
    "Good: whole intact person moving behind Jesus; visible text: FOLLOW ME.",
    "Bad: broken person; visible text: DESTROY YOURSELF.",
    "",
    "Example D — dense list:",
    "Narration: Releasing the idol. Forgiving the enemy. Rejecting the compromise. Asking for help. Leaving the danger.",
    "Good: split into more than one scene; preserve exact script order; use literal actions from the text; no invented umbrella labels.",
    "Bad: one board; five mini-scenes; RELEASE / REFUSE / SEEK.",
    "",
    "Viewer application scenes:",
    "When the assigned scriptText shifts from the biblical moment to the audience using words like we, our, us, you, your, most of us, or maybe you, consider representing ordinary people as viewer stand-ins.",
    "",
    "Do not default to an abstract board just because the line is theological.",
    "",
    "Use `avatar` when:",
    "- the narration is about what we believe, feel, assume, fear, reduce, measure, or misunderstand",
    "- the line applies the biblical truth to the viewer",
    "- the scene needs human emotion, identification, or self-recognition",
    "- the viewer should see themselves in the idea",
    "",
    "Modern application framing:",
    "When scriptText shifts to the viewer using we, our, us, you, or your, do not default to biblical-era figures.",
    "",
    "Usually prefer contemporary or timeless-contemporary ordinary people as viewer stand-ins.",
    "",
    "These people should feel like:",
    "- present-day believers",
    "- ordinary men or women",
    "- small groups, families, or individuals",
    "- people in recognizable human situations such as prayer, waiting, reflection, uncertainty, disappointment, or hope",
    "",
    "Do not place modern application figures physically inside the biblical event unless the narration explicitly imagines that.",
    "",
    "Instead:",
    "- keep the people contemporary",
    "- keep the application emotionally recognizable",
    "- preserve biblical anchoring through secondary references, not time-collapse",
    "",
    "Biblical anchoring may appear through restrained secondary references named or implied by the current script, such as:",
    "- an open Bible",
    "- a prayer journal",
    "- a church bench",
    "- a dim room with morning light",
    "- a path, light, door, table, or other restrained biblical echo from the narration",
    "- a nearby Bible passage reference if the scene format allows text",
    "",
    "The application scene should feel like our world being interpreted by biblical truth, not our world inserted literally into a biblical setting.",
    "",
    "Application alignment:",
    "When scriptText is about the audience rather than the biblical event, the image should first represent the human application clearly.",
    "",
    "Ask:",
    "- what would this look like in the life of a present-day believer?",
    "- what posture, setting, or object would show this struggle?",
    "- can the viewer recognize themselves in the scene?",
    "",
    "Only after that, add restrained biblical echoes if useful.",
    "Do not let biblical symbolism overpower the viewer-identification.",
    "",
    "Viewer stand-ins should be:",
    "- anonymous ordinary believers or simple human figures",
    "- reverent, non-photorealistic, watercolor and ink",
    "- emotionally clear but not melodramatic",
    "- not celebrity-like",
    "- not stock-photo modern",
    "- not overly specific unless the scriptText names a specific life situation",
    "",
    "For viewer-application scenes, prefer a non-text `avatar` scene when the emotional and conceptual meaning can be shown through people, posture, and setting.",
    "",
    "Use a text-based card only if the concept cannot be made clear enough visually.",
    "",
    "Scripture card content:",
    "When a scene is a scripture/reference card, do not show only the Bible reference unless the narration only provides a reference.",
    "",
    "If the assigned scriptText includes verse wording or a clear excerpt, show a short exact excerpt from the scriptText plus the reference.",
    "",
    "Use short verse excerpts, usually 3 to 10 words.",
    "Do not invent Bible text from memory.",
    "Do not rewrite the verse unless the exact words are already in scriptText.",
    "If the verse is long, use the most relevant short phrase from the assigned scriptText.",
    "",
    "Label-to-visual matching:",
    "For every visible label, include a corresponding visual element that directly represents that label.",
    "Do not place labels over generic decoration.",
    "Do not use one general symbol for several different labels if the labels express different ideas.",
    "",
    "Creative restrictions (do not paste into imagePrompt — app owns negatives):",
    "",
    "- Avoid photorealism, 3D, glossy digital art, cinematic realism, neon, clutter, watermarks, random text, celebrity likeness.",
    "- Jesus must be reverent, simple, non-photorealistic, and not theatrical.",
    "",
    "### ImagePrompt requirements for inserts",
    "",
    "A normal insert imagePrompt body must:",
    "- be approximately 40–80 words (app adds style lock + negatives)",
    "- describe the final concrete composition",
    "- name the exact large elements",
    "- define whether text is present (no-text line OR exact visible text)",
    "- omit the style lock and photorealism/3D/watermark negatives (app-owned)",
    "- avoid theological explanations",
    "- avoid pasting the complete scriptText",
    "- avoid telling Flow to interpret, choose, summarize, or identify the important elements",
    "",
    "Bad prompt behavior:",
    "Directly illustrate this exact narration fragment and choose the most representative elements.",
    "",
    "Good prompt behavior (body only):",
    "One rough Roman crossbeam lies on packed earth beside one large iron nail, with the shadow of a Roman guard crossing both. The image must read immediately as an execution instrument, not decorative Christian symbolism. No visible text, captions, letters, or words.",
    "",
    "The planner must make the visual decision before writing the prompt.",
    "Flow should render the composition, not design the teaching logic.",
    "",
    buildGodsWordImagePromptBodyContract(),
    "",
    "Body-only examples (app adds style lock + negatives):",
    "",
    "avatar/space body:",
    "A present-day believer kneels beside a simple bed, hands open in quiet trust, warm parchment light on the room. One focal idea.",
    "",
    "insert object body:",
    "One rough Roman crossbeam lies on packed earth beside one large iron nail, with the shadow of a Roman guard crossing both. The image must read as an execution instrument, not decorative Christian symbolism. No visible text, captions, letters, or words.",
    "",
    "insert card body:",
    "Clean Bible-study card. Use only this exact visible text: Follow Me. No other words. Simple centered hand-lettered layout with one quiet path behind the words.",
    "",
    "Chapter covers should feel like designed chapter cards, not generic quote cards.",
    "Normal inserts should not feel like mini chapter covers.",
    "Do not write long theological explanations inside imagePrompt.",
    "",
    "### Insert-specific QA gate",
    "",
    "Scene quality checklist:",
    "Before outputting each scene, silently check:",
    "- Does this image represent the exact assigned scriptText, not just the general topic?",
    "- Is the scene concrete enough for the viewer to understand the narration?",
    "- If this is a space scene, is it a concrete place, pause, or transition tied to the line?",
    "- If this is an insert, does it avoid looking like a chapter cover unless it is one?",
    "- If this is a symbol, is it named, implied, or necessary for explaining the line?",
    "- If this is a viewer application, can the viewer recognize themselves in the situation?",
    "- If this has labels, does each label have a matching visual element?",
    "- Does the prompt avoid decorative religious filler?",
    "- Does it preserve visual variety without sacrificing meaning?",
    "- Is the prompt concise?",
    "",
    "Every normal insert must fail QA and be rewritten when any of the following is true:",
    "- it communicates more than one principal claim",
    "- it contains more than four large elements",
    "- it contains mini-scenes or panels",
    "- visible text exceeds the allowed budget",
    "- visible text is not exact wording from the current scriptText",
    "- visible text comes from a rejected or negated statement",
    "- it uses invented umbrella labels",
    "- it imports a conclusion from later narration",
    "- visualIdea is meta rather than concrete",
    "- imagePrompt asks Flow to choose or interpret the meaning",
    "- the complete narration fragment is pasted inside imagePrompt",
    "- a human application has been forced into an abstract board",
    "- the image requires reading several labels before its basic meaning is clear",
    "- the scene cannot reasonably be understood within its assigned duration",
    "",
    "Also check the full sequence:",
    "- no more than two text-based inserts consecutively",
    "- chapter covers do not count toward this limit",
    "- no more than three consecutive object/detail inserts when another valid format exists",
    "- soft target: about 15% to 25% of normal inserts as text cards when exact text exists",
    "- repeated inserts must change the teaching action, not merely the arrangement",
    "- insert variety must never override semantic simplicity",
    "- every visualIdea begins with an allowed format prefix",
    "",
    "visualPurpose: one short sentence explaining why the scene exists in the sequence.",
    "visualIdea: one plain visual sentence that starts with an allowed format prefix; for chapter covers use Chapter cover: [EXACT TITLE], with [one central visual].",
  ].join("\n");
}

/**
 * Compact planner context for fill-hybrid (local skeleton owns scriptText + segmentation).
 * Keeps each ChatGPT turn under the inline composer limit (~8k) — no file attachment.
 */
export function buildTheGodsWordFillHybridContext() {
  return [
    "## TheGodsWord fill-chunk context",
    "",
    "Illustrated Bible-study explainer in hand-painted watercolor/ink on warm paper.",
    "The app injects the production style lock and negatives after you return imagePrompt bodies.",
    "",
    "The scene skeleton was built locally — scriptText and duration are authoritative.",
    "Fill ONLY visualPurpose, visualIdea, imagePrompt, sceneType, and optional fishSpeechText.",
    "Do NOT re-segment, rewrite scriptText, invent scenes, or omit orders.",
    "",
    "### visualIdea format prefixes (required)",
    "",
    "Every visualIdea MUST begin with exactly one of:",
    "- Narrative scene:",
    "- Object/detail insert:",
    "- Chapter cover:",
    "- Concept card:",
    "- Scripture/reference card:",
    "- Comparison card:",
    "- Simple diagram:",
    "- Question card:",
    "- Word-study card:",
    "- Atmosphere/space:",
    "",
    "Examples:",
    "Object/detail insert: One phone lighting beside an open Bible while a loose seed rests on the page.",
    "Chapter cover: GENESIS 3, with one restrained parchment bookplate and a single central visual.",
    "",
    "### Chapter / final covers",
    "",
    "Exact [CHAPTER N - TITLE] and [FINAL — TITLE] markers become insert covers with spoken scriptText.",
    "visualIdea: Chapter cover: [EXACT TITLE], with [one central visual].",
    "One central illustration only — no subtitle, panels, or extra labels on covers.",
    "",
    "### Variety (soft)",
    "",
    "Prefer concrete objects/places/people over generic skies or decorative filler.",
    "No more than two text-based inserts in a row (chapter covers excluded).",
    "Match identity/style locks from Continuity when provided.",
    "",
    buildGodsWordImagePromptBodyContract(),
    "",
    "visualPurpose: one short sentence explaining why the scene exists.",
    "visualIdea: one concrete drawable sentence with an allowed prefix.",
  ].join("\n");
}

export function buildTheGodsWordTimingRules() {
  return [
    "## Timing Rules",
    "",
    "Duration is stored as whole seconds. Use integer values only (for example 3, 4, 5, 6, 7, 8).",
    "Minimum duration is 2 seconds only for rare indivisible beats; prefer the floors below.",
    "",
    "Global word-floor:",
    "- Never plan a single-word scene anywhere.",
    "- Avoid 1–3 word scenes except exact short quotes / word-study emphasis (otherwise merge with the neighbor).",
    "",
    "Hook scenes ([HOOK] only): usually 3 to 6 seconds.",
    "- Use 3 seconds for very brief micro-beats (still ≥4 words when possible)",
    "- Use 4 seconds for questions and short actions",
    "- Use 5 seconds for emotionally important hook beats",
    "- Use 6 seconds only for an exceptionally dense hook clause",
    "- Do not merge independent hook beats merely to pad duration",
    "",
    "Body scenes (CHAPTER / body / FINAL spoken): usually 5 to 8 seconds.",
    "- Soft floor: 5–6 seconds",
    "- Prefer 6–8 seconds",
    "- Soft ceiling: 8 seconds (do not plan 9–11s body scenes)",
    "- Target about 15–25 narrated words per body scene",
    "- Prefer merging same-claim clauses over micro-splitting",
    "",
    "Use shorter durations in the hook to keep the opening visually engaging.",
    "Do not use body-length scenes in the hook unless the hook line is unusually long.",
    "In body sections, do NOT apply Hard hook micro-splitting.",
    "Narrative segmentation wins over empty padding — but body segmentation is moderate, not hook-aggressive.",
    "",
    "Hard hook beat segmentation (HOOK ONLY):",
    "In the hook, one scene = one recognizable narrative beat.",
    "Do not merge two rhetorical questions.",
    "Do not merge setup with reversal/consequence.",
    "Separate parallel progressions such as You read / You hear / You recognize.",
    "Never merge independent hook beats merely to reach 4–6 seconds.",
    "Never keep four or more independent hook sentences in one scene as a compact list.",
    "Never emit a one-word hook scene.",
  ].join("\n");
}

/** Compact context for section-chunked Visual Plan Batch (not the fat Project Bible packet). */
export function buildTheGodsWordSectionHybridContext() {
  return [
    buildTheGodsWordFlowVisualBrief(),
    buildTheGodsWordTimingRules(),
    [
      "## Section-chunk mode notes",
      "",
      "This request plans ONE script section only.",
      "Still obey Soft distribution guidance for the whole video using the accumulated scene-type mix provided with each chunk.",
      "Do not rebalance only inside this section if that would push the full-video mix into extremes.",
      "imagePrompt is BODY ONLY — the app adds style lock + negatives (and no-text for avatar/space).",
      "Never invent cinematic/photoreal/3D scene openings in the body.",
      "Do not paste style-lock or No-photorealism negatives into imagePrompt.",
    ].join("\n"),
  ].join("\n\n");
}

export function buildTheGodsWordGenerationModeInstructions(
  mode: ChatGptGenerationMode,
) {
  if (mode === "FULL_VIDEO") {
    return [
      "GENERATION MODE:",
      "Generate the full visual plan for the complete script.",
      "Create one chapter-cover insert for every exact [CHAPTER N - TITLE] marker.",
      "Create one final-cover insert for [FINAL — TITLE].",
      "[HOOK] does not create a cover.",
      "Each chapter cover must be the first scene of that section and use the exact marker title with no subtitle.",
      "Return a JSON array only.",
    ].join("\n");
  }

  if (mode === "HOOK_TEST") {
    return [
      "GENERATION MODE:",
      "Generate only the hook scenes from the [HOOK]…[END HOOK] block when present, otherwise from the opening retention section.",
      "Apply Hard hook segmentation before choosing formats.",
      "[HOOK] does not create a cover.",
      "Do not force chapter covers in the hook.",
      "Return a JSON array only.",
    ].join("\n");
  }

  if (mode === "TEN_SCENE_TEST") {
    return [
      "GENERATION MODE:",
      "Generate only the first 10 scenes from the script.",
      "Include a chapter cover only if one of the first 10 scenes begins at an exact [CHAPTER N - TITLE] or [FINAL — TITLE] marker.",
      "[HOOK] does not create a cover.",
      "Return a JSON array only.",
    ].join("\n");
  }

  if (mode === "SEGMENTED_BY_PERCENT") {
    return [
      "GENERATION MODE:",
      "Generate scenes only for the Current Script Segment.",
      "Include a chapter cover only if this segment begins at an exact [CHAPTER N - TITLE] or [FINAL — TITLE] marker.",
      "[HOOK] does not create a cover.",
      "Return a JSON array only.",
    ].join("\n");
  }

  return [
    "GENERATION MODE:",
    "Generate only the hook scenes from the opening retention section.",
    "Focus on the opening 45 to 120 seconds depending on script length.",
    "Return a JSON array only.",
  ].join("\n");
}

/** Distinctive phrases that must appear in the generated request. */
export const THE_GODS_WORD_INSERT_CONTRACT_MARKERS = [
  "Normal insert production contract",
  "Complexity budget by duration",
  "Hard hook segmentation (HOOK ONLY)",
  "Moderate body segmentation",
  "Global word-floor",
  "visualIdea format prefixes (required)",
  "Positive insert-format triggers",
  "Visible-text policy (per format)",
  "Soft insert-format balance",
  "Script coverage lock",
  "Structural labels never go in scriptText",
  "JSON safety (hard rule)",
  "Negation/correction rule",
  "Dense-list split example",
  "Insert-specific QA gate",
  "Every exact marker matching [CHAPTER N - TITLE] must create one chapter-cover insert (digits may be 1 or 01; dash may be - or —).",
  "[FINAL — TITLE] must also create one final-cover insert.",
  "[HOOK] does not create a cover.",
  "RELEASE / REFUSE / SEEK",
  "DESTROY YOURSELF",
  "FOLLOW ME",
] as const;

/** Old instructions that must no longer appear. */
export const THE_GODS_WORD_REMOVED_INSERT_MARKERS = [
  "Chapter markers in the script do not automatically require section opener cards",
  "2 to 4 short labels",
  "small supporting illustrations",
  "usually 2 to 8 words",
  "intentionally one compact list",
  "rare concept or question cards only when exact short text is essential",
] as const;
