/**
 * Final production imagePrompt contract for The Bible in One Year.
 * Injected into the Visual Planner request; the app never rewrites prompts.
 */

export const BIBLE_ONE_YEAR_HOST_CHARACTER_LOCK =
  "Recurring American pastor host: about 55–65, warm fair complexion, short neatly kept silver-gray hair with slightly darker sides, closely trimmed salt-and-pepper beard, calm brown or hazel eyes, gentle expression lines around the eyes and forehead, softly defined facial features, medium build, open-collar dusty-blue cotton shirt beneath a warm beige lightweight cardigan, relaxed upright posture, restrained welcoming smile, painted as simplified watercolor-and-ink storybook forms without photorealism or celebrity likeness";

export const BIBLE_ONE_YEAR_LISTENER_CHARACTER_LOCK =
  "Recurring older listener: about 65–80, soft white or gray hair, warm complexion, quiet lined face, receptive eyes, modest knit sweater, calm seated or standing posture, simplified watercolor treatment without celebrity likeness";

export const BIBLE_ONE_YEAR_ADAM_CHARACTER_LOCK =
  "Adam as a dignified first man: youthful adult, short dark hair, warm olive-tan complexion, strong but gentle features, simple unadorned biblical-era wrap, respectful non-erotic framing with natural modesty, watercolor-and-ink storybook treatment";

export const BIBLE_ONE_YEAR_EVE_CHARACTER_LOCK =
  "Eve as a dignified first woman: youthful adult, long dark hair, warm olive-tan complexion, calm features, simple unadorned biblical-era wrap, respectful non-erotic framing with natural modesty, watercolor-and-ink storybook treatment";

export const BIBLE_ONE_YEAR_STYLE_LOCK_AVATAR =
  "16:9 horizontal hand-painted watercolor and ink Bible-study illustration on warm off-white textured paper, with soft sketch outlines, muted earth tones, wheat gold, olive green, dusty blue shadows, burnt umber, and gentle parchment light.";

export const BIBLE_ONE_YEAR_STYLE_LOCK_INSERT =
  "16:9 horizontal hand-painted watercolor and ink object-detail insert on warm off-white textured paper, with soft sketch outlines, muted earth tones, wheat gold, olive green, dusty blue shadows, burnt umber, and gentle parchment light.";

export const BIBLE_ONE_YEAR_STYLE_LOCK_LANDSCAPE =
  "16:9 horizontal hand-painted watercolor and ink Bible-study landscape on warm off-white textured paper, with soft sketch outlines, muted earth tones, wheat gold, olive green, dusty blue shadows, burnt umber, and gentle parchment light.";

export const BIBLE_ONE_YEAR_STYLE_LOCK_INTERIOR =
  "16:9 horizontal hand-painted watercolor and ink Bible-study interior on warm off-white textured paper, with soft sketch outlines, muted earth tones, wheat gold, olive green, dusty blue shadows, burnt umber, and gentle parchment light.";

/** Generic chapter / preview / reflection parchment bookplate cover. */
export const BIBLE_ONE_YEAR_STYLE_LOCK_COVER =
  "16:9 horizontal hand-painted watercolor and ink refined biblical bookplate cover on warm off-white textured paper. A single large aged warm-ivory parchment sheet is centered against a clean off-white background, with irregular deckled edges, subtle creases, faint stains, worn corners, and a soft natural shadow beneath it. Soft sketch outlines, muted parchment cream, wheat gold, olive green, pale dusty blue, soft terracotta, burnt umber, and gentle natural light.";

/** Episode cover with pastor — same parchment family, named distinctly for requests. */
export const BIBLE_ONE_YEAR_STYLE_LOCK_EPISODE_COVER =
  "16:9 horizontal hand-painted watercolor and ink refined biblical episode bookplate cover on warm off-white textured paper. A single large aged warm-ivory parchment sheet is centered against a clean off-white background, with irregular deckled edges, subtle creases, faint stains, worn corners, and a soft natural shadow beneath it. Soft sketch outlines, muted parchment cream, wheat gold, olive green, pale dusty blue, soft terracotta, burnt umber, and gentle natural light.";

export const BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT =
  "No photorealism, 3D rendering, glossy digital art, cinematic realism, dramatic movie lighting, neon, excessive clutter, watermark, logo, celebrity likeness, stock-photo styling, anime, comic-book styling, plastic textures, modern advertising design, infographic layout, miniature panels, or decorative religious filler.";

export const BIBLE_ONE_YEAR_VISIBLE_TEXT_NONE =
  "No readable writing, visible text, captions, letters, numbers, logos, or words.";

export const BIBLE_ONE_YEAR_OPEN_BIBLE_PAGE_GUARD =
  "The page layout and line structure may be suggested, but all printed or handwritten wording must remain indistinct and unreadable.";

export const BIBLE_ONE_YEAR_VISIBLE_TEXT_PHRASE_PREFIX =
  "visible text limited to:";

/**
 * Full FINAL IMAGE PROMPT CONTRACT for first-pass production output.
 * Character locks are injected verbatim so the planner can copy them into prompts.
 */
export function buildBibleOneYearFinalImagePromptContract() {
  return [
    "FINAL IMAGE PROMPT CONTRACT — FIRST-PASS PRODUCTION OUTPUT",
    "",
    "The imagePrompt returned in every scene is the final production prompt.",
    "It will be sent directly to the image-generation model without rewriting, compilation, expansion, correction, access to the other scene fields, or access to this visual brief.",
    "",
    "Therefore every imagePrompt must be:",
    "* standalone;",
    "* complete;",
    "* production-ready;",
    "* visually specific;",
    "* consistent with the channel style;",
    "* understandable without reading scriptText, visualPurpose, or visualIdea.",
    "",
    "Never return a short base prompt, shorthand prompt, placeholder, summary, or prompt that depends on later processing.",
    "",
    "Do not assume that another system will add:",
    "* aspect ratio;",
    "* art medium;",
    "* palette;",
    "* character continuity;",
    "* composition instructions;",
    "* text restrictions;",
    "* negative restrictions;",
    "* Bible-page safety;",
    "* title restrictions.",
    "",
    "All necessary information must already appear inside every imagePrompt.",
    "",
    "FINAL PROMPT ORDER",
    "",
    "Construct each imagePrompt in this order:",
    "1. format and visual style;",
    "2. principal subject and framing;",
    "3. observable action or visual state;",
    "4. spatial relationship and script-specific detail;",
    "5. CONCRETE SEMANTIC EVIDENCE and clarification when needed;",
    "6. composition guard;",
    "7. Bible-page or character-continuity rule when applicable;",
    "8. visible-text rule;",
    "9. negative restrictions.",
    "",
    "1. FORMAT AND STYLE LOCK",
    "",
    "Every prompt must begin with exactly one complete style lock appropriate to the scene.",
    "",
    "Avatar scene — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_AVATAR,
    "",
    "Insert scene without a cover — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_INSERT,
    "",
    "Landscape or exterior space — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_LANDSCAPE,
    "",
    "Interior space — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_INTERIOR,
    "",
    "Chapter / reading-preview / reflection parchment cover — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_COVER,
    "",
    "Episode cover with the recurring American pastor host — begin with:",
    BIBLE_ONE_YEAR_STYLE_LOCK_EPISODE_COVER,
    "",
    "Do not use generic phrases such as:",
    "* warm watercolor aesthetic;",
    "* cinematic Bible art;",
    "* beautiful biblical scene;",
    "* peaceful spiritual image;",
    "* title card;",
    "* reading card;",
    "* source card;",
    "* flat title card;",
    "* UI panel;",
    "* poster;",
    "* slide;",
    "* modern advertising layout.",
    "",
    "2. FINAL COMPOSITION",
    "",
    "After the style lock, describe the final still image.",
    "Every prompt must identify:",
    "* one principal person, object, relationship, or environment;",
    "* the framing or point of view;",
    "* where the focal subject appears in the frame;",
    "* one observable action, gesture, transformation, or visual state;",
    "* one distinctive detail tied specifically to the assigned narration.",
    "",
    "Valid framing language includes:",
    "close view; overhead close view; medium view; medium-wide view; rear three-quarter view; side profile; ground-level view; low-horizon view; high aerial view; elevated wide view; expansive landscape view; waist-up view.",
    "",
    "3. CONCRETE SEMANTIC EVIDENCE",
    "",
    "Every imagePrompt must include concrete semantic evidence before any abstract claim:",
    "* one concrete principal subject, object, or environment;",
    "* one framing or point of view;",
    "* one physically observable action or state;",
    "* at least one visible detail taken specifically from the assigned scriptText;",
    "* a semantic clarification when the action could be misread.",
    "",
    "Prompts must not depend on abstract-only expressions such as:",
    "* representing trust;",
    "* showing purpose;",
    "* symbolizing reflection;",
    "* communicating order;",
    "* illustrating grace;",
    "* an image about failure;",
    "* a peaceful spiritual scene.",
    "",
    "Those phrases may appear only after the physical evidence is described.",
    "",
    "Incorrect:",
    "A symbolic scene representing trust in God’s design.",
    "",
    "Correct:",
    "Rear three-quarter view of the older listener holding one small section of an unfinished woven pattern while the remaining design continues beyond the edge of the table. The visible fragment should communicate limited understanding rather than confusion.",
    "",
    "4. ONE PRINCIPAL CLAIM",
    "",
    "Every image must communicate one principal narration beat.",
    "ONE INDEPENDENT VISUAL ACTION, TRANSFORMATION, EMOTIONAL BEAT, TEMPORAL CHANGE, OR LOCATION CHANGE PER SCENE.",
    "Use the most appropriate composition guard:",
    "* One focal idea.",
    "* One focal relationship.",
    "* One principal claim and one dominant composition.",
    "* Keep the scene as one continuous action.",
    "* Keep all named elements within one coherent environment.",
    "* No miniature panels.",
    "* No split-screen composition.",
    "* No boxed comparison.",
    "* No secondary explanatory layer.",
    "* No infographic layout.",
    "* No decorative supporting symbols.",
    "* Do not narrate a full sequence inside one still frame.",
    "",
    "Do not use panels merely because the script contains several clauses.",
    "Several large elements may appear only when they are explicitly named in the assigned scriptText. They must remain part of one unified environment or one relationship around a dominant focal subject.",
    "",
    "5. SEMANTIC AND EMOTIONAL CLARIFICATION",
    "",
    "When a gesture or image could be misunderstood, explicitly state the intended reading.",
    "Examples:",
    "* The emotion should read as concern rather than despair.",
    "* The gesture should show reception rather than refusal.",
    "* The posture should communicate stewardship rather than conquest.",
    "* Keep the moment reverent rather than theatrical.",
    "* The imagined danger must remain visibly separate from the real environment.",
    "* The solitude should feel compassionate rather than hopeless.",
    "* The light should suggest divine presence without depicting God as a visible figure.",
    "* The stillness should feel restful rather than empty.",
    "* The expression should show recognition rather than confusion.",
    "* The scene should communicate ordinary human weakness without guilt or negligence.",
    "Do not use written labels to communicate the emotional meaning.",
    "",
    "6. SCRIPTURE-READING SAFETY",
    "",
    "During narrated Scripture:",
    "* use literal, calm, first-century or creation-era imagery;",
    "* never use a modern listener as a substitute for a biblical figure;",
    "* never depict God as a visible human person;",
    "* never show a giant hand, face, body, silhouette, or anthropomorphic figure representing God;",
    "* divine action may be suggested through light, wind, breath, movement, order, growth, or environmental change;",
    "* avoid theatrical fantasy, supernatural spectacle, sermon imagery, guilt imagery, horror, or cinematic battle energy.",
    "",
    "7. OPEN BIBLE SAFETY",
    "",
    "Whenever an open Bible, edition page, journal, calendar, note, or document is visible and no readable text is authorized, include:",
    BIBLE_ONE_YEAR_OPEN_BIBLE_PAGE_GUARD,
    "",
    "Do not allow invented verses, random lettering, fake Bible quotations, readable chapter names, signatures, captions, or legible reflection notes.",
    "Handwritten reflection notes may appear only when the script calls for them, and their writing must remain intentionally illegible.",
    "",
    "8. CHARACTER CONTINUITY",
    "",
    "When a recurring person appears, repeat the complete approved character description inside every relevant imagePrompt.",
    "Do not rely only on labels such as pastor, older host, older listener, Adam, Eve, first man, or first woman.",
    "",
    "Pastor host character lock (copy verbatim; fixed appearance, beard, and clothing — no optional alternatives):",
    BIBLE_ONE_YEAR_HOST_CHARACTER_LOCK,
    "",
    "Listener character lock:",
    BIBLE_ONE_YEAR_LISTENER_CHARACTER_LOCK,
    "",
    "Adam character lock:",
    BIBLE_ONE_YEAR_ADAM_CHARACTER_LOCK,
    "",
    "Eve character lock:",
    BIBLE_ONE_YEAR_EVE_CHARACTER_LOCK,
    "",
    "When a recurring character is present:",
    "* use the applicable character-lock wording verbatim;",
    "* preserve age, hair, skin tone, facial features, clothing, and build;",
    "* do not silently change appearance between scenes;",
    "* do not add a celebrity likeness;",
    "* do not use optional beard, alternate shirt colors, alternate garments, or different age ranges;",
    "* do not apply modern clothing to biblical characters;",
    "* do not apply biblical clothing to the modern pastor or listener;",
    "* do NOT add “no modern clothing” or “no modern objects” when the pastor or modern listener appears — that contradicts the approved modern wardrobe.",
    "",
    "When no approved character lock applies, avoid claiming exact continuity and use a non-recurring generic figure appropriate to the assigned scene.",
    "",
    "9. MODESTY AND BIBLICAL HUMAN FIGURES",
    "",
    "For Adam and Eve:",
    "* use respectful non-erotic biblical representation;",
    "* preserve natural modesty through framing, foliage, distance, hair, pose, water, or foreground elements;",
    "* do not use modern clothing;",
    "* do not create sensual poses;",
    "* do not use shame imagery before the narration introduces shame;",
    "* show innocence, dignity, companionship, or vulnerability according to the assigned line.",
    "",
    "10. VISIBLE TEXT",
    "",
    "Visible text is forbidden unless the scene belongs to an explicitly authorized cover, progress insert, next-reading insert, or short authorized avatar text (AMEN / THANK YOU).",
    "",
    "Scene without authorized text — end the prompt with:",
    BIBLE_ONE_YEAR_VISIBLE_TEXT_NONE,
    "",
    "Scene with authorized title — end the positive text instruction with exactly:",
    `${BIBLE_ONE_YEAR_VISIBLE_TEXT_PHRASE_PREFIX} TITLE.`,
    "Then add:",
    "No other readable writing, captions, letters, numbers, logos, or words.",
    "",
    "Keep the validator-sensitive phrase exactly as:",
    `${BIBLE_ONE_YEAR_VISIBLE_TEXT_PHRASE_PREFIX} TITLE.`,
    "",
    "Do not replace it with:",
    "* Visible text must be exactly;",
    "* exact readable text;",
    "* title text;",
    "* text arranged as;",
    "* title on two lines.",
    "",
    "The authorized title must appear as one literal uninterrupted sequence inside imagePrompt, even when the visual model may arrange letters across lines.",
    "Never add subtitles, episode descriptions, Bible quotations, decorative words, section explanations, author names, channel names, extra chapter numbers, or punctuation not present in the authorized title.",
    "Do not place quotation marks around the authorized title.",
    "Do not use CLOSING as an on-screen title.",
    "",
    "11. NEGATIVE LOCK",
    "",
    "Every prompt must end with a negative lock.",
    "Default negative lock:",
    BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT,
    "",
    "Add scene-specific exclusions only when useful (examples: no visible deity; no graphic anatomy; no sensual framing; no theatrical Jesus; no violent imagery; no horror atmosphere; no map labels; no readable page text).",
    "Do not contradict the positive composition.",
    "Never add “no modern clothing” or “no modern objects” to pastor/listener modern avatar scenes.",
    "",
    "12. PROMPT LENGTH AND DENSITY",
    "",
    "Prompts should normally use:",
    "* simple chapter / preview / reflection parchment covers: approximately 105 to 150 words;",
    "* episode covers containing the pastor: approximately 140 to 190 words;",
    "* simple non-cover scenes: approximately 80 to 120 words;",
    "* scenes with a contrast or several directly narrated elements: approximately 100 to 145 words.",
    "",
    "Do not reject parchment covers merely for exceeding an older 65–95 word cover range.",
    "These are guidance ranges, not reasons to add filler.",
    "Every phrase must control format, medium, composition, framing, subject, action, spatial relationship, character continuity, emotion, semantic clarity, visible text, or exclusions.",
    "Do not pad prompts with decorative adjectives.",
    "",
    "13. PROMPT INDEPENDENCE TEST",
    "",
    "Before returning each scene, silently verify:",
    "Could the image-generation model create the intended image correctly if it received only this imagePrompt and none of the other JSON fields?",
    "If the answer is no, complete the prompt before returning the JSON.",
    "",
    "14. PARCHMENT COVER DESIGN SYSTEM",
    "",
    "Every cover must contain:",
    "* large classical dark-brown serif title in the upper half;",
    "* very small symmetrical hand-drawn ornamental flourishes;",
    "* a delicate watercolor illustration integrated into the lower half;",
    "* an open Bible as a recurring lower focal element;",
    "* generous negative space;",
    "* an airy handcrafted appearance;",
    "* exact authorized visible text;",
    "* Bible-page wording indistinct and unreadable.",
    "",
    "Episode cover:",
    "* include the recurring American pastor host at one side of the title;",
    "* waist-up or medium presentation;",
    "* one gently open hand presenting the title;",
    "* do not cover or superimpose the title;",
    "* lower illustration may show sunrise, water, fields, or the day’s biblical theme.",
    "",
    "Chapter cover:",
    "* no pastor by default;",
    "* lower watercolor environment must be tied literally to the chapter;",
    "* title in upper half;",
    "* open Bible in lower half.",
    "",
    "Reading preview cover:",
    "* same parchment family;",
    "* lower illustration previews the reading without revealing several unrelated events.",
    "",
    "Reflection cover:",
    "* lower half includes open Bible, reflection slip or card, pencil, calm water or distant hills;",
    "* communicate completion and transition rather than study pressure;",
    "* visible text limited to: REFLECT AND PRAY.",
    "",
    "Disallow in all covers:",
    "* table or room interior as the main composition;",
    "* chair as the main composition;",
    "* full-bleed landscape;",
    "* flat title card;",
    "* UI panel;",
    "* poster;",
    "* slide;",
    "* modern advertising layout;",
    "* title placed outside the parchment;",
    "* several miniature scenes;",
    "* title rendered on a separate floating label.",
    "",
    "Cover example (chapter parchment — not a table title card):",
    `${BIBLE_ONE_YEAR_STYLE_LOCK_COVER} Large classical dark-brown serif title occupies the upper half of the centered parchment sheet with tiny symmetrical hand-drawn flourishes. In the lower half, a delicate watercolor of first light over still waters rests above an open Bible with indistinct page wording. Generous negative space and an airy handcrafted bookplate appearance. ${BIBLE_ONE_YEAR_OPEN_BIBLE_PAGE_GUARD} ${BIBLE_ONE_YEAR_VISIBLE_TEXT_PHRASE_PREFIX} GENESIS 1. No other readable writing, captions, letters, numbers, logos, or words. ${BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT}`,
    "",
    "15. NON-COVER PROMPT EXAMPLE",
    "",
    "Script beat: God said, Let there be light, and there was light.",
    "",
    "Correct final imagePrompt:",
    `${BIBLE_ONE_YEAR_STYLE_LOCK_LANDSCAPE.replace("dusty blue shadows", "dusty blue-black shadows")} Wide low-horizon view across primordial dark waters as one pure burst of wheat-gold light opens through the darkness and strikes the surface, creating a clear radiant division across the water. No human figure or visible representation of God appears. Keep the event solemn and immediate rather than explosive or cinematic. One focal event and one dominant composition. ${BIBLE_ONE_YEAR_VISIBLE_TEXT_NONE} ${BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT}`,
    "",
    "16. FINAL SILENT VALIDATION",
    "",
    "Before returning the JSON array, verify every scene:",
    "* the imagePrompt is final rather than abbreviated;",
    "* it begins with a valid complete style lock;",
    "* it explicitly states 16:9 horizontal;",
    "* it specifies watercolor and ink;",
    "* it has one principal visual claim;",
    "* it contains CONCRETE SEMANTIC EVIDENCE;",
    "* it contains a framing or viewpoint;",
    "* it contains an observable action or visual state;",
    "* it contains one narration-specific detail;",
    "* it is understandable without the other scene fields;",
    "* its emotion cannot be easily misread;",
    "* it includes an applicable composition guard;",
    "* any recurring character contains the correct character lock;",
    "* pastor/listener scenes do not say no modern clothing;",
    "* any open Bible has unreadable printed wording unless text is authorized;",
    "* it contains exactly one coherent visible-text rule using the exact phrase visible text limited to: TITLE. when text is authorized;",
    "* any visible title matches the authorized title exactly;",
    "* it contains no additional visible wording;",
    "* it contains a negative lock;",
    "* it does not depict God as a visible person;",
    "* it does not contradict itself;",
    "* it is not exactly duplicated by another scene;",
    "* it does not ask for later compilation or correction;",
    "* it does not merge several independent visual actions into one frame.",
    "",
    "Return the complete final JSON array only after all scenes pass this validation.",
  ].join("\n");
}
