/**
 * Compact visual brief for The Bible in One Year category.
 * Used by visual-plan scoring/revision and compact scene requests.
 *
 * Keep this contract self-contained so the model does not mix in
 * TheGodsWord [CHAPTER N - TITLE] / [FINAL — TITLE] marker systems.
 */
import type { ChatGptGenerationMode } from "@/lib/chatgpt-scene-handoff";
import { BIBLE_ONE_YEAR_REFLECTION_OPENER } from "@/lib/the-bible-in-one-year-compact-script";
import {
  BIBLE_ONE_YEAR_HOST_CHARACTER_LOCK,
  BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT,
  BIBLE_ONE_YEAR_OPEN_BIBLE_PAGE_GUARD,
  BIBLE_ONE_YEAR_STYLE_LOCK_COVER,
  BIBLE_ONE_YEAR_STYLE_LOCK_EPISODE_COVER,
  buildBibleOneYearFinalImagePromptContract,
} from "@/lib/the-bible-in-one-year-final-image-prompt-contract";

export function buildBibleOneYearVisualBrief() {
  return [
    "## The Bible in One Year Visual Brief",
    "",
    "FORMAT PRIORITY RULE",
    "",
    "This request uses the compact-flow Bible in One Year format only.",
    "Ignore marker systems from other formats unless those markers actually appear in the provided script.",
    "Do not invent [CHAPTER N - TITLE], [FINAL — TITLE], silent covers, or scenes not grounded in spoken lines.",
    "",
    "Priority order (higher wins on conflict):",
    "1. JSON validity and importer compatibility",
    "2. Exact spoken script coverage",
    "3. No silent / empty scriptText scenes",
    "4. Correct section and chapter-cover behavior",
    "5. Allowed scene schema and sceneType values",
    "6. Visual-first storytelling, text-by-sceneType limits, and visual quality",
    "",
    "Conflict clarifications:",
    "- Cover / progress title text is an intentional exception to Visual-First for designated insert scenes only.",
    "- visualIdea prefix Chapter cover: is a schema label. It does NOT mean the imagePrompt should say card.",
    "- Prefer image-first language in imagePrompt even when visualIdea uses Chapter cover:.",
    "",
    "JSON AND IMPORTER COMPATIBILITY RULES",
    "",
    "Return a strict valid JSON array only. No markdown, no explanations, no wrapper object, no trailing commas.",
    "Every string value must be safe for fragile JSON importers.",
    "",
    "Hard quote rule:",
    "1. Never put raw unescaped straight double quotes inside any JSON string.",
    "2. In scriptText, never use backslash-escaped quotes like \\\".",
    "3. If the spoken script contains straight double quotes, encode each one as \\u0022.",
    "4. After JSON.parse, those \\u0022 sequences must become normal quotation marks in spoken text.",
    "5. Curly quotes (“ ”) may remain only when they already appear in the source spoken script (common in WEBUS).",
    "6. Do not add new quotation marks of any kind in imagePrompt, visualIdea, or visualPurpose.",
    "",
    "Example spoken line in source script:",
    "To mark your progress, comment \"Day 1 complete\" below.",
    "",
    "Correct scriptText JSON fragment:",
    '"scriptText": "To mark your progress, comment \\u0022Day 1 complete\\u0022 below."',
    "",
    "Incorrect:",
    '"scriptText": "To mark your progress, comment \\"Day 1 complete\\" below."',
    '"scriptText": "To mark your progress, comment "Day 1 complete" below."',
    "",
    "SCRIPT COVERAGE RULE",
    "",
    "Every spoken word must be covered exactly once, in original narration order.",
    "You may split long paragraphs at natural sentence or clause boundaries.",
    "Do not paraphrase, summarize, omit, reorder, or invent narration.",
    "Structural labels are excluded from narration and must never appear in scriptText.",
    "Validation: join parsed scriptText values in order and compare to the source script with structural labels removed and whitespace normalized.",
    "",
    "VISUAL-BEAT SEGMENTATION PHASE",
    "",
    "Before writing any imagePrompt, segment the spoken script into visual beats.",
    "Core rule: ONE INDEPENDENT VISUAL ACTION, TRANSFORMATION, EMOTIONAL BEAT, TEMPORAL CHANGE, OR LOCATION CHANGE PER SCENE.",
    "",
    "Split a line or paragraph when it contains any of:",
    "- more than one successive observable action;",
    "- an action and its visual result;",
    "- a change of dominant subject;",
    "- a change of location;",
    "- a change of time;",
    "- an important emotional change;",
    "- an enumeration whose elements need different compositions;",
    "- a transition between intention, action, and consequence;",
    "- several narrative verbs that cannot be shown clearly in one still frame.",
    "",
    "Mandatory Eve fruit example:",
    "When the woman saw that the tree was good for food ... she took some of its fruit, and ate. Then she gave some to her husband ... and he ate it, too. Their eyes were opened ... They sewed fig leaves together...",
    "",
    "Must split into 7 scenes:",
    "1. Eve observes the fruit.",
    "2. Eve reaches for and takes the fruit.",
    "3. Eve eats.",
    "4. Eve gives fruit to Adam.",
    "5. Adam eats.",
    "6. They recognize their nakedness.",
    "7. They make coverings from fig leaves.",
    "",
    "Do not summarize, paraphrase, omit, or repeat narration while splitting. Keep exact spoken script coverage.",
    "",
    "Flexible word targets:",
    "- Introduction, reflection, and closing: normally 6–18 spoken words per scene.",
    "- Narrative Scripture: normally 8–22 spoken words per scene.",
    "- Genealogies or one continuous descriptive state: may reach 18–35 words.",
    "- Always review any scene with more than 24 words.",
    "- Most scenes should last 3–7 seconds.",
    "- Use 7–9 seconds only for contemplative states or one continuous action that truly needs it.",
    "- Do not use long durations as justification to merge independent visual actions.",
    "",
    "Do not impose a rigid total scene count. Prefer about one scene per clear visual action.",
    "",
    "SECTION AND COVER RULES",
    "",
    "Structural labels are never narrated and never copied into scriptText.",
    "A label never creates a silent scene.",
    "",
    "Markers that may appear in this format:",
    "- [INTRODUCTION]",
    "- [CHAPTER COVER — BOOK CHAPTER]",
    "- [REFLECTION AND PRAYER]",
    "- [CLOSING]",
    "- [HOOK] / [END HOOK] (segmentation only; never covers; never replace INTRODUCTION)",
    "",
    "[INTRODUCTION]:",
    "- The explicit episode-title spoken line becomes the parchment episode cover with pastor.",
    "- If there is no explicit episode-title line, the first welcome / day-identification line becomes that cover.",
    "- Never create a silent cover.",
    "- Never create a cover with empty scriptText.",
    "",
    "[CHAPTER COVER — …]:",
    "- The chapter announcement becomes a parchment chapter cover.",
    "- Never create an empty scene before it.",
    "- If a chapter announcement appears without a label, it is still a chapter-cover scene.",
    "",
    "[REFLECTION AND PRAYER]:",
    "- The first spoken line becomes a parchment reflection cover.",
    "- Exact visible title: REFLECT AND PRAY.",
    `- The standard opener is: ${BIBLE_ONE_YEAR_REFLECTION_OPENER}`,
    "",
    "[CLOSING] is segmentation only:",
    "- It must NOT create a cover.",
    "- It must NOT force sceneType insert.",
    "- It must NOT force-insert a silent or titled CLOSING scene.",
    "- The first spoken closing line should normally be the pastor thank-you avatar scene.",
    "- Remove CLOSING from authorized titles.",
    "",
    "Fallback when [INTRODUCTION] is missing:",
    "If categoryFormat is bible-in-one-year and the first spoken line before Scripture reading welcomes the day or identifies the series day, treat that line as the narrated introduction / episode cover anyway.",
    "",
    "Chapter cover example:",
    "Spoken line: Genesis, chapter 1.",
    'sceneType: "insert"',
    "visualIdea: Chapter cover: GENESIS 1, with a restrained parchment bookplate composition",
    "scriptText: Genesis, chapter 1.",
    `imagePrompt: begin with ${BIBLE_ONE_YEAR_STYLE_LOCK_COVER} then a parchment chapter cover with large classical dark-brown serif title in the upper half, delicate lower watercolor tied to the chapter, open Bible with indistinct page wording, visible text limited to: GENESIS 1, then the negative lock.`,
    "",
    "Episode cover note:",
    `Begin with ${BIBLE_ONE_YEAR_STYLE_LOCK_EPISODE_COVER} and include ${BIBLE_ONE_YEAR_HOST_CHARACTER_LOCK} verbatim, presenting the title with one open hand without blocking the text.`,
    "",
    "Visible title may simplify (GENESIS 1). scriptText must keep the spoken wording (Genesis, chapter 1.).",
    "",
    "SCENE TYPE MEANING",
    "",
    'Use only: "avatar", "insert", or "space".',
    "- avatar: recurring American pastor host, older listener, biblical people, human gesture or emotion",
    "- insert: parchment covers, close objects/details, short title/progress inserts",
    "- space: landscapes, environments, creation scenes, quiet rooms without a dominant character focus",
    "",
    "VISUAL-FIRST RULE",
    "",
    "The image does the primary storytelling. Visible text is secondary and rare.",
    "If a scene communicates clearly without text, do not add visible text.",
    "Prefer: one meaningful object, one biblical environment, one human gesture, one focused detail.",
    "",
    "TEXT BY SCENE TYPE",
    "",
    "avatar:",
    "- Default: No visible text.",
    "- Rare exception only: 1 to 3 essential words.",
    "- Authorized short avatar text: AMEN and THANK YOU.",
    "",
    "space:",
    "- Default: No visible text.",
    "- Environment/action must carry the meaning.",
    "- Rare exception only: 2 to 3 essential words.",
    "",
    "insert:",
    "- Default for Scripture-reading inserts: No visible text.",
    "- Covers and short progress/next-reading inserts may include essential title text.",
    "- Non-cover inserts: prefer 1 to 4 words max when text is truly needed.",
    "- Only these insert classes may exceed 4 words when necessary:",
    "  a) episode / chapter / reflection covers",
    "  b) progress title inserts (DAY N COMPLETE)",
    "  c) next-reading title inserts (NEXT — GENESIS 3–5)",
    "",
    "COVER AND TITLE TEXT RULE",
    "",
    "When an insert or authorized avatar beat is allowed to show text, show only the essential title. No subtitle. No explanatory sentence. No decorative supporting words.",
    "",
    "Allowed on-screen titles (UPPERCASE, no quotation marks):",
    "- THE BIBLE IN ONE YEAR — DAY N",
    "- reading preview titles such as GENESIS 3–5",
    "- chapter titles such as GENESIS 1 / GENESIS 2 / GENESIS 1–2",
    "- REFLECT AND PRAY",
    "- AMEN",
    "- THANK YOU",
    "- DAY N COMPLETE",
    "- NEXT — GENESIS 3–5 (or the dynamic next-reading title)",
    "",
    "Never use CLOSING as an on-screen title.",
    "Never use REFLECTION AND PRAYER or PRAYER as on-screen titles; use REFLECT AND PRAY.",
    "",
    "Canonical imagePrompt phrases for text:",
    "- No text: No readable writing, visible text, captions, letters, numbers, logos, or words.",
    "- With text: visible text limited to: TITLE.",
    "- Then: No other readable writing, captions, letters, numbers, logos, or words.",
    "",
    "Keep the validator-sensitive phrase exactly as:",
    "visible text limited to: TITLE.",
    "",
    "Do not write:",
    'visible text limited to: "GENESIS 1"',
    "exact readable visible text: Day 1 complete.",
    "Use only this exact visible text: ...",
    "Visible text must be exactly ...",
    "title text arranged as ...",
    "title on two lines.",
    "",
    "Spoken scriptText preserves original casing/punctuation. On-screen title may be normalized to the short UPPERCASE form.",
    "",
    "ANTI-REPETITION RULE (intro / reflection / closing)",
    "",
    "Do not use the same seated-pastor + open-Bible + warm-room + soft-light composition in three consecutive intro/reflection/closing scenes.",
    "Vary composition, not only adjectives. Alternate among:",
    "wide room with no dominant character | close hands | listening profile | overhead object view | page detail | figure by a window | placing a ribbon marker | object that embodies the narrated action | biblical landscape transition when the line calls for it.",
    "Every variation must still match the current scriptText.",
    "When the pastor or older listener appears, copy the approved character lock verbatim into imagePrompt.",
    "",
    "ABSTRACT BEAT VISUAL MAPPINGS",
    "",
    "Release pressure / not needing perfection:",
    "Prefer a human close-up: hands relaxing, shoulders lowering, a page no longer gripped tightly, or a calm exhale. Avoid another full seated-pastor composition.",
    "",
    "Listen, receive, and return:",
    "Show attentive posture + open Bible + a ribbon marker placed for the next reading. The marker is a narrative detail, not the only element.",
    "",
    "Carry one thought:",
    "Show one marked passage, a tiny reflection note, or a marker tied to a specific line. Note handwriting must be illegible. Avoid a generic bookmark with no reflective link.",
    "",
    "Identify translation / WEBUS / edition:",
    "Focus on a title page, edition page, or publication detail. Layout may be visible; printed wording stays indistinct when No readable writing applies. Avoid only open-Bible-plus-glasses.",
    "",
    "Rest / stillness / presence:",
    "Do not default to praying hands. Consider an empty chair beside a Bible, a still cup, quiet light in a room, or open resting hands. Choose one dominant image.",
    "",
    buildBibleOneYearFinalImagePromptContract(),
    "",
    "DETERMINISTIC PASTOR + CLOSING MAPPINGS",
    "",
    "Match by spoken line, semantic intent, and section — never by hardcoded scene numbers.",
    "Keep the older-listener lock when the listener appears, but do not substitute the listener for the pastor in deterministic pastor beats.",
    "",
    "1. Episode title / intro cover:",
    "   sceneType insert; parchment episode cover with pastor presenting the title with one open hand; do not block or superimpose the title.",
    "2. First personal welcome after the episode cover:",
    "   sceneType avatar; pastor beside an open Bible, gently inviting the listener toward an empty chair.",
    "3. Worthwhile pause (then the time we have spent together will already have been worthwhile):",
    "   sceneType avatar; pastor and older listener sharing a quiet reflective pause; no applause or celebratory gesture.",
    "4. Pray with me:",
    "   sceneType avatar; pastor bows beside the open Bible; empty chair may remain visible.",
    "5. Amen (In Jesus’ name, amen.):",
    "   sceneType avatar; pastor lifts his head slightly after prayer with a peaceful expression; visible text limited to: AMEN.",
    "6. Thank-you closing line:",
    "   sceneType avatar; pastor thanks the listener beside a closed Bible with ribbon visible; visible text limited to: THANK YOU; never a CLOSING cover.",
    "7. Progress:",
    "   object-detail or parchment-like progress insert; visible text limited to: DAY N COMPLETE.",
    "8. Share:",
    "   listener writing one short reflection; handwriting intentionally illegible; no additional visible text.",
    "9. Next reading:",
    "   insert with Bible ribbon moving to the next passage; visible text limited to: NEXT — …",
    "10. Final blessing:",
    "    quiet interior or peaceful space; Bible remains in soft light; no visible text; no pastor required unless the script calls for him.",
    "",
    "IMAGE PROMPT STYLE",
    "",
    "Describe image first, then text if allowed.",
    "Do not begin with: card, source card, reading plan card, comment card, WEBUS card.",
    "Obey FINAL IMAGE PROMPT CONTRACT for every scene. imagePrompt is first-pass production output.",
    "",
    "VISUAL QUALITY RULES",
    "",
    "Warm watercolor-and-ink Bible study aesthetic: peaceful, reverent, clear, uncluttered, easy for listeners over 65.",
    "One clear focal idea per scene. No crowded symbolism, abstract religious clichés, or repeated generic images.",
    "",
    "During Scripture reading:",
    "- Literal, calm visuals tied to the narrated text",
    "- No modern listener stand-ins",
    "- No sermon energy, guilt imagery, or dramatic fantasy",
    "- Never depict God as a visible human figure",
    "- Prefer landscapes, objects, animals, light, water, plants, garden scenes, respectful biblical figures when the text needs them",
    "- Obey visual-beat segmentation: one independent action per scene",
    "",
    "During introduction, reflection, prayer, and closing:",
    "- Modern pastor and older-adult stand-ins allowed",
    "- Quiet rooms, open Bibles, warm morning/evening light",
    "- Gentle, companionable, reassuring tone",
    "- Still obey ANTI-REPETITION RULE and ABSTRACT BEAT VISUAL MAPPINGS",
    "- When host or listener appears, copy the approved character lock verbatim into imagePrompt",
    "- Recurring American pastor host and Recurring older listener locks live in FINAL IMAGE PROMPT CONTRACT",
    "- Adam as a dignified first man: and Eve as a dignified first woman: locks live in FINAL IMAGE PROMPT CONTRACT",
    "",
    "VISUALIDEA PREFIXES",
    "",
    "Every visualIdea must start with exactly one allowed prefix:",
    "- Narrative scene:",
    "- Object/detail insert:",
    "- Chapter cover:",
    "- Atmosphere/space:",
    "- Concept card: (rare; discouraged for this category)",
    "- Scripture/reference card: (rare; discouraged for this category)",
    "",
    "Prefer Chapter cover: for episode / chapter / reflection covers only — NOT for [CLOSING].",
    "Prefer Narrative scene: / Object/detail insert: / Atmosphere/space: for body scenes.",
    "Even when using Chapter cover:, write imagePrompt as an image-first parchment composition, not a card template or table title card.",
    "",
    "DURATION GUIDANCE",
    "",
    "Whole seconds only. Minimum 2.",
    "Episode / chapter covers: about 4 to 7 seconds.",
    "Reflection cover: about 6 to 8 seconds.",
    "Body scenes: mostly 3 to 7 seconds.",
    "Use 7 to 9 seconds only for contemplative states or one continuous action that truly needs it.",
    "Scripture reading: split by independent visual actions — do not keep multi-action reading as one long 6–11 second scene.",
    "Do not merge independent beats only to pad duration.",
  ].join("\n");
}

export function buildBibleOneYearOutputRequirementsSection() {
  return [
    "## Output Requirements",
    "",
    "Return a strict valid JSON array only.",
    "No markdown. No explanations. No wrapper object. No trailing commas.",
    "",
    "Schema example (parchment chapter cover with spoken voiceover — not a table title card):",
    "",
    "[",
    "{",
    '"order": 1,',
    '"scriptText": "Genesis, chapter 1.",',
    '"sceneType": "insert",',
    '"visualPurpose": "Open the chapter with the spoken announcement",',
    '"visualIdea": "Chapter cover: GENESIS 1, with a restrained parchment bookplate composition",',
    '"duration": 5,',
    `"imagePrompt": "${BIBLE_ONE_YEAR_STYLE_LOCK_COVER} Large classical dark-brown serif title occupies the upper half of the centered parchment sheet with tiny symmetrical hand-drawn flourishes. In the lower half, a delicate watercolor of first light over still waters rests above an open Bible with indistinct page wording. Generous negative space and an airy handcrafted bookplate appearance. ${BIBLE_ONE_YEAR_OPEN_BIBLE_PAGE_GUARD} visible text limited to: GENESIS 1. No other readable writing, captions, letters, numbers, logos, or words. ${BIBLE_ONE_YEAR_NEGATIVE_LOCK_DEFAULT}",`,
    '"status": "planned"',
    "}",
    "]",
    "",
    'Every sceneType must be exactly "avatar", "insert", or "space".',
    "Do not invent other sceneType values or new fields.",
    "status is always planned.",
    "",
    "imagePrompt is FINAL first-pass production output. Obey FINAL IMAGE PROMPT CONTRACT. The app validates and stores imagePrompt without rewriting.",
    "",
    "Hard quote rule reminder:",
    "In scriptText encode spoken straight quotes as \\u0022. Never use raw \" or \\\" in scriptText.",
    "Never add quotation marks in imagePrompt / visualIdea / visualPurpose.",
    "",
    "Visual text reminder:",
    "avatar/space default to No readable writing, visible text, captions, letters, numbers, logos, or words.",
    "Covers and progress/next-reading inserts may use: visible text limited to: TITLE",
    "AMEN and THANK YOU are allowed as short avatar text.",
    "Do not use card-first wording or table title cards in imagePrompt.",
    "Do not create empty scriptText covers.",
    "Structural labels must never appear in scriptText.",
    "Never create a CLOSING cover.",
  ].join("\n");
}

export function buildBibleOneYearTimingRules() {
  return [
    "## Timing Rules",
    "",
    "Duration is stored as whole seconds. Use integers only. Minimum duration is 2 seconds.",
    "",
    "Cover / chapter announcement openers: usually 4 to 7 seconds.",
    "Reflection cover: usually 6 to 8 seconds.",
    "Body scenes: mostly 3 to 7 seconds.",
    "Contemplative or one continuous action: 7 to 9 seconds only when truly needed.",
    "Scripture reading: split by independent visual actions — do not keep multi-action reading as one long duration.",
    "Introduction and closing body beats: usually 3 to 7 seconds, following visual-beat segmentation.",
    "",
    "Do not merge independent beats only to justify a longer duration.",
    "Visual-beat segmentation wins over duration padding.",
  ].join("\n");
}

/** Compact context for section-chunked Visual Plan Batch (Bible in One Year). */
export function buildBibleOneYearSectionHybridContext() {
  return [
    buildBibleOneYearVisualBrief(),
    buildBibleOneYearTimingRules(),
    [
      "## Section-chunk mode notes",
      "",
      "This request plans ONE script section only.",
      "Obey the Bible in One Year style locks and cover contracts from the brief above.",
      "Use the accumulated scene-type mix to keep full-video rhythm balanced; do not rebalance only inside this section.",
      "Never invent cinematic/photoreal/3D styles.",
    ].join("\n"),
  ].join("\n\n");
}

export function buildBibleOneYearGenerationModeInstructions(
  mode: ChatGptGenerationMode,
) {
  const shared = [
    "Follow the Bible in One Year Visual Brief only.",
    "Use only markers and spoken lines present in the provided script.",
    "Do not invent [CHAPTER N - TITLE], [FINAL — TITLE], or empty covers.",
    "Chapter announcements such as Genesis, chapter 1. are chapter-cover scenes with voiceover.",
    "[HOOK] and [END HOOK] do not create covers and must not erase [INTRODUCTION].",
    "[CLOSING] is segmentation only and must never create a cover.",
    "Obey Deterministic Visual Beats when present.",
    "Obey visual-beat segmentation: ONE INDEPENDENT VISUAL ACTION, TRANSFORMATION, EMOTIONAL BEAT, TEMPORAL CHANGE, OR LOCATION CHANGE PER SCENE.",
    "Return a JSON array only.",
  ];

  if (mode === "FULL_VIDEO") {
    return [
      "GENERATION MODE:",
      "Generate the full visual plan for the complete Bible in One Year script.",
      ...shared,
    ].join("\n");
  }

  if (mode === "HOOK_TEST") {
    return [
      "GENERATION MODE:",
      "Generate only the opening retention / hook scenes when [HOOK]…[END HOOK] is present; otherwise the introduction opener and early intro beats.",
      ...shared,
    ].join("\n");
  }

  if (mode === "TEN_SCENE_TEST") {
    return [
      "GENERATION MODE:",
      "Generate only the first 10 scenes from the script.",
      ...shared,
    ].join("\n");
  }

  if (mode === "SEGMENTED_BY_PERCENT") {
    return [
      "GENERATION MODE:",
      "Generate scenes only for the Current Script Segment.",
      ...shared,
    ].join("\n");
  }

  return [
    "GENERATION MODE:",
    "Generate scenes for the provided script using Bible in One Year rules.",
    ...shared,
  ].join("\n");
}

/** Distinctive phrases that must appear in the Bible in One Year brief. */
export const BIBLE_ONE_YEAR_VISUAL_BRIEF_MARKERS = [
  "FORMAT PRIORITY RULE",
  "JSON AND IMPORTER COMPATIBILITY RULES",
  "Hard quote rule:",
  "encode each one as \\u0022",
  "SCRIPT COVERAGE RULE",
  "VISUAL-BEAT SEGMENTATION",
  "SECTION AND COVER RULES",
  "Never create a cover with empty scriptText.",
  "VISUAL-FIRST RULE",
  "TEXT BY SCENE TYPE",
  "COVER AND TITLE TEXT RULE",
  "FINAL IMAGE PROMPT CONTRACT — FIRST-PASS PRODUCTION OUTPUT",
  "CONCRETE SEMANTIC EVIDENCE",
  "ANTI-REPETITION RULE (intro / reflection / closing)",
  "ABSTRACT BEAT VISUAL MAPPINGS",
  "IMAGE PROMPT STYLE",
  "Do not begin with: card, source card",
  "VISUALIDEA PREFIXES",
  "visible text limited to: TITLE",
  "Fallback when [INTRODUCTION] is missing:",
  "Recurring American pastor host:",
  "Recurring older listener:",
  "Adam as a dignified first man:",
  "Eve as a dignified first woman:",
  "REFLECT AND PRAY",
  "[CLOSING] is segmentation only",
] as const;
